different counties are also going to need different industries--not all are using the level of industries

too much to do by county - going by region

In [1]:
import pandas as pd
import numpy as np

Load and brief clean of EDD data

In [2]:
full_edd = pd.read_csv('Current_EDD_1121.csv')

In [3]:
full_edd['Area Name'] = full_edd['Area Name'].str.replace(' County', '')

Load county info data to get regions in the EDD dataset

In [56]:
county_info = pd.read_csv('~/classes/CAFWD/job_quality_index/data/county_to_regions_key.csv')

In [57]:
county_info.head()

   FIPS  COUNTYFIP        County Rural/Urban   Regions
0  6001          1       Alameda       Urban  Bay Area
1  6013         13  Contra Costa       Urban  Bay Area
2  6095         95        Solano       Urban  Bay Area
3  6081         81     San Mateo       Urban  Bay Area
4  6085         85   Santa Clara       Urban  Bay Area

Merge counties and EDD

In [59]:
full_edd_regions = pd.merge(full_edd, county_info, left_on='Area Name', right_on='County')

In [60]:
full_edd_regions.head(10)

,Area Type,Area Name,Year,Month,Date,Series Code,Industry Title,Seasonally Adjusted,Current Employment,FIPS,COUNTYFIP,County,Rural/Urban,Regions
0,County,Alameda,2014,January,01/01/2014,6000000,Goods Producing,N,100000,6001,1,Alameda,Urban,Bay Area
1,County,Alameda,2014,January,01/01/2014,70710000,"Arts, Entertainment, and Recreation",N,8800,6001,1,Alameda,Urban,Bay Area
2,County,Alameda,2014,January,01/01/2014,80000000,Other Services,N,24400,6001,1,Alameda,Urban,Bay Area
3,County,Alameda,2014,January,01/01/2014,65000000,Educational and Health Services,N,110700,6001,1,Alameda,Urban,Bay Area
4,County,Alameda,2014,January,01/01/2014,50000000,Information,N,13900,6001,1,Alameda,Urban,Bay Area
5,County,Alameda,2014,January,01/01/2014,65620000,Health Care and Social Assistance,N,95300,6001,1,Alameda,Urban,Bay Area
6,County,Alameda,2014,January,01/01/2014,70000000,Leisure and Hospitality,N,61800,6001,1,Alameda,Urban,Bay Area
7,County,Alameda,2014,January,01/01/2014,32000000,Nondurable Goods,N,21100,6001,1,Alameda,Urban,Bay Area
8,County,Alameda,2014,January,01/01/2014,42000000,Retail Trade,N,68500,6001,1,Alameda,Urban,Bay Area
9,County,Alameda,2014,January,01/01/2014,60560000,Administrative and Support and Waste Ser,N,35200,6001,1,Alameda,Urban,Bay Area

For testing, reduce down to December 2020

In [62]:
edd_test_2020 = full_edd_regions.loc[full_edd_regions['Date'] == '12/01/2020']

In [63]:
edd_test_2020 = edd_test_2020.loc[edd_test_2020['Seasonally Adjusted'] == 'N']

In [64]:
total_nonfarm = edd_test_2020.loc[edd_test_2020['Series Code'] == 0]

In [65]:
edd_test_2020 = edd_test_2020.loc[edd_test_2020['Series Code'] != 0]

In [66]:
edd_test_2020 = edd_test_2020.reset_index()

In [67]:
edd_test_2020

,index,Area Type,Area Name,Year,Month,Date,Series Code,Industry Title,Seasonally Adjusted,Current Employment,FIPS,COUNTYFIP,County,Rural/Urban,Regions
0,2656,County,Alameda,2020,December,12/01/2020,50000000,Information,N,19500,6001,1,Alameda,Urban,Bay Area
1,2657,County,Alameda,2020,December,12/01/2020,65000000,Educational and Health Services,N,122700,6001,1,Alameda,Urban,Bay Area
2,2658,County,Alameda,2020,December,12/01/2020,60560000,Administrative and Support and Waste Ser,N,38000,6001,1,Alameda,Urban,Bay Area
3,2659,County,Alameda,2020,December,12/01/2020,32000000,Nondurable Goods,N,20900,6001,1,Alameda,Urban,Bay Area
4,2660,County,Alameda,2020,December,12/01/2020,65620000,Health Care and Social Assistance,N,109400,6001,1,Alameda,Urban,Bay Area
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2013,674059,County,Yuba,2020,December,12/01/2020,70000000,Leisure and Hospitality,N,1000,6115,115,Yuba,Rural,Sacramento
2014,674060,County,Yuba,2020,December,12/01/2020,80000000,Other Services,N,300,6115,115,Yuba,Rural,Sacramento
2015,674061,County,Yuba,2020,December,12/01/2020,42000000,Retail Trade,N,1400,6115,115,Yuba,Rural,Sacramento
2016,674062,County,Yuba,2020,December,12/01/2020,50000000,Information,N,100,6115,115,Yuba,Rural,Sacramento
2017,674063,County,Yuba,2020,December,12/01/2020,65000000,Educational and Health Services,N,3700,6115,115,Yuba,Rural,Sacramento

In [68]:
edd_test_2020['Current Employment'].sum()

89599820

TARGET ISH COUNT OF WHAT TOTAL EMPLOYMENT SHOULD BE

In [69]:
len(total_nonfarm)

58

In [70]:
total_nonfarm['Current Employment'].sum()

15779100

In [71]:
edd_test_2020.loc[edd_test_2020['Series Code'] == 11000000]['Current Employment'].sum() # total farm

359520

In [16]:
target = 15779100 + 359520 # total farm + total nonfarm
target

16138620

Group by regions

In [79]:
edd_regions_2020 = edd_test_2020.groupby(['Regions', 'Industry Title', 'Series Code']).sum().reset_index()

In [81]:
edd_regions_2020 = edd_regions_2020[['Regions', 'Industry Title', 'Series Code', 'Current Employment']]

In [82]:
edd_regions_2020

,Regions,Industry Title,Series Code,Current Employment
0,Bay Area,Accommodation and Food Service,70720000,155800
1,Bay Area,Administrative and Support Services,60561000,14500
2,Bay Area,Administrative and Support and Waste Ser,60560000,187300
3,Bay Area,"Arts, Entertainment, and Recreation",70710000,19400
4,Bay Area,Beverage and Tobacco Product Mfg,32312000,10100
...,...,...,...,...
701,Sierra Nevada,Total Private,5000000,69850
702,Sierra Nevada,Total Wage and Salary,1000000,105950
703,Sierra Nevada,"Trade, Transportation and Utilities",40000000,15530
704,Sierra Nevada,"Transportation, Warehousing and Utilitie",43000000,1910
705,Sierra Nevada,Wholesale Trade,41000000,980

Create dataframes for each region to cut different industries for each one

In [85]:
edd_regions_2020['Regions'].unique()

array(['Bay Area', 'Central Coast', 'Central Valley', 'Inland Empire',
       'Los Angeles', 'Orange', 'Redwood Coast', 'Sacramento',
       'San Diego-Imperial', 'Shasta / Cascades', 'Sierra Nevada'],
      dtype=object)

In [88]:
ba_2020 = edd_regions_2020.loc[edd_regions_2020['Regions'] == 'Bay Area'].sort_values('Series Code')
cc_2020 = edd_regions_2020.loc[edd_regions_2020['Regions'] == 'Central Coast'].sort_values('Series Code')
cv_2020 = edd_regions_2020.loc[edd_regions_2020['Regions'] == 'Central Valley'].sort_values('Series Code')
ie_2020 = edd_regions_2020.loc[edd_regions_2020['Regions'] == 'Inland Empire'].sort_values('Series Code')
la_2020 = edd_regions_2020.loc[edd_regions_2020['Regions'] == 'Los Angeles'].sort_values('Series Code')
oc_2020 = edd_regions_2020.loc[edd_regions_2020['Regions'] == 'Orange'].sort_values('Series Code')
rc_2020 = edd_regions_2020.loc[edd_regions_2020['Regions'] == 'Redwood Coast'].sort_values('Series Code')
sac_2020 = edd_regions_2020.loc[edd_regions_2020['Regions'] == 'Sacramento'].sort_values('Series Code')
sd_2020 = edd_regions_2020.loc[edd_regions_2020['Regions'] == 'San Diego-Imperial'].sort_values('Series Code')
shas_2020 = edd_regions_2020.loc[edd_regions_2020['Regions'] == 'Shasta / Cascades'].sort_values('Series Code')
sn_2020 = edd_regions_2020.loc[edd_regions_2020['Regions'] == 'Sierra Nevada'].sort_values('Series Code')

Bay Area

In [89]:
ba_2020

,Regions,Industry Title,Series Code,Current Employment
49,Bay Area,Total Wage and Salary,1000000,3698700
48,Bay Area,Total Private,5000000,413700
20,Bay Area,Goods Producing,6000000,555700
40,Bay Area,Service Providing,7000000,3128400
34,Bay Area,Private Service Providing,8000000,323400
30,Bay Area,Mining and Logging,10000000,800
47,Bay Area,Total Farm,11000000,14600
31,Bay Area,"Natural Resources, Mining and Constructi",15000000,152200
7,Bay Area,Construction,20000000,83300
42,Bay Area,Specialty Trade Contractors,20238000,10300
29,Bay Area,Manufacturing,30000000,353700
10,Bay Area,Durable Goods,31000000,253600
32,Bay Area,Nondurable Goods,32000000,88600
4,Bay Area,Beverage and Tobacco Product Mfg,32312000,10100
50,Bay Area,"Trade, Transportation and Utilities",40000000,540400
52,Bay Area,Wholesale Trade,41000000,104700
39,Bay Area,Retail Trade,42000000,314700
18,Bay Area,Food and Beverage Stores,42445000,11000
6,Bay Area,Clothing and Clothing Accessories Stores,42448000,1900
19,Bay Area,General Merchandise Stores,42452000,7200
51,Bay Area,"Transportation, Warehousing and Utilitie",43000000,121000
23,Bay Area,Information,50000000,246400
16,Bay Area,Financial Activities,55000000,191700
15,Bay Area,Finance and Insurance,55520000,128400
37,Bay Area,Real Estate and Rental and Leasing,55530000,51700
35,Bay Area,Professional and Business Services,60000000,760400
36,Bay Area,"Professional, Scientific and Technical S",60540000,483800
28,Bay Area,Management of Companies and Enterprises,60550000,64700
2,Bay Area,Administrative and Support and Waste Ser,60560000,187300
1,Bay Area,Administrative and Support Services,60561000,14500
12,Bay Area,Educational and Health Services,65000000,594700
11,Bay Area,Educational Services,65610000,88500
22,Bay Area,Health Care and Social Assistance,65620000,481200
24,Bay Area,Leisure and Hospitality,70000000,245700
3,Bay Area,"Arts, Entertainment, and Recreation",70710000,19400
0,Bay Area,Accommodation and Food Service,70720000,155800
17,Bay Area,Food Services and Drinking Places,70722000,26100
38,Bay Area,Restaurants,70722500,9900
33,Bay Area,Other Services,80000000,97300
21,Bay Area,Government,90000000,451800
13,Bay Area,Federal Government,90910000,46700
14,Bay Area,Federal Government excluding Department of Def...,90912991,700
9,Bay Area,Department of Defense,90919110,0
43,Bay Area,State Government,90920000,96600
44,Bay Area,State Government Education,90921611,2000
45,Bay Area,State Government Excluding Education,90922000,8200
25,Bay Area,Local Government,90930000,308500
26,Bay Area,Local Government Education,90931611,27000
27,Bay Area,Local Government Excluding Education,90932000,26100
41,Bay Area,Special Districts plus Indian Tribes,90932994,7500
8,Bay Area,County,90939012,11700
5,Bay Area,City,90939022,6900
46,Bay Area,State and Local Government,90940000,66900

In [90]:
ba_2020['Current Employment'].sum() # before cutting down

15096100

In [105]:
ba_codes = [10000000, 11000000, 15000000, 20000000, 30000000, 41000000, 42000000, 43000000, 50000000, 60540000, 60550000, 60560000, 65000000, 70000000, 80000000, 90910000, 90920000, 90930000]

In [106]:
ba_test = ba_2020.loc[ba_2020['Series Code'].isin(ba_codes)]

In [107]:
ba_test['Current Employment'].sum()

3516700

Central Coast

In [108]:
cc_2020

,Regions,Industry Title,Series Code,Current Employment
106,Central Coast,Total Wage and Salary,1000000,908200
105,Central Coast,Total Private,5000000,647700
77,Central Coast,Goods Producing,6000000,107000
97,Central Coast,Service Providing,7000000,708100
92,Central Coast,Private Service Providing,8000000,545000
88,Central Coast,Mining and Logging,10000000,1800
104,Central Coast,Total Farm,11000000,93100
89,Central Coast,"Natural Resources, Mining and Constructi",15000000,46400
62,Central Coast,Construction,20000000,33500
99,Central Coast,Specialty Trade Contractors,20238000,10900
87,Central Coast,Manufacturing,30000000,59000
66,Central Coast,Durable Goods,31000000,34200
61,Central Coast,Computer and Electronic Product Manufact,31334000,5200
90,Central Coast,Nondurable Goods,32000000,20300
58,Central Coast,Chemical Manufacturing,32325000,3200
107,Central Coast,"Trade, Transportation and Utilities",40000000,148400
110,Central Coast,Wholesale Trade,41000000,29800
96,Central Coast,Retail Trade,42000000,98400
75,Central Coast,Food and Beverage Stores,42445000,18500
60,Central Coast,Clothing and Clothing Accessories Stores,42448000,5900
76,Central Coast,General Merchandise Stores,42452000,5900
109,Central Coast,"Transportation, Warehousing and Utilitie",43000000,20200
108,Central Coast,Transportation and Warehousing,43400089,5500
80,Central Coast,Information,50000000,9900
73,Central Coast,Financial Activities,55000000,33400
72,Central Coast,Finance and Insurance,55520000,19600
64,Central Coast,Credit Intermediation and Related Activi,55522000,7200
81,Central Coast,Insurance Carriers and Related,55524000,3200
95,Central Coast,Real Estate and Rental and Leasing,55530000,9700
93,Central Coast,Professional and Business Services,60000000,116000
94,Central Coast,"Professional, Scientific and Technical S",60540000,29600
86,Central Coast,Management of Companies and Enterprises,60550000,10800
56,Central Coast,Administrative and Support and Waste Ser,60560000,39300
55,Central Coast,Administrative and Support Services,60561000,17100
69,Central Coast,Employment Services,60561300,7700
68,Central Coast,Educational and Health Services,65000000,131900
67,Central Coast,Educational Services,65610000,2600
79,Central Coast,Health Care and Social Assistance,65620000,45200
82,Central Coast,Leisure and Hospitality,70000000,87600
57,Central Coast,"Arts, Entertainment, and Recreation",70710000,2900
54,Central Coast,Accommodation and Food Service,70720000,77400
53,Central Coast,Accommodation,70721000,11100
74,Central Coast,Food Services and Drinking Places,70722000,35000
91,Central Coast,Other Services,80000000,25100
78,Central Coast,Government,90000000,155800
70,Central Coast,Federal Government,90910000,19000
71,Central Coast,Federal Government excluding Department of Def...,90912991,1700
65,Central Coast,Department of Defense,90919110,10100
100,Central Coast,State Government,90920000,35500
101,Central Coast,State Government Education,90921611,22900
102,Central Coast,State Government Excluding Education,90922000,12400
83,Central Coast,Local Government,90930000,101300
84,Central Coast,Local Government Education,90931611,40800
85,Central Coast,Local Government Excluding Education,90932000,46400
98,Central Coast,Special Districts plus Indian Tribes,90932994,10600
63,Central Coast,County,90939012,18700
59,Central Coast,City,90939022,8400
103,Central Coast,State and Local Government,90940000,133900

In [109]:
cc_2020['Current Employment'].sum() # before cutting down

4896000

In [123]:
cc_codes = [10000000, 11000000, 15000000, 20000000, 30000000, 41000000, 42000000, 43000000, 55000000, 60000000, 65000000, 70000000, 80000000, 90910000, 90920000, 90930000]

In [124]:
cc_test = cc_2020.loc[cc_2020['Series Code'].isin(cc_codes)]

In [125]:
cc_test['Current Employment'].sum()

932000

Central Valley

In [118]:
pd.set_option('display.max_rows', None)
cv_2020

,Regions,Industry Title,Series Code,Current Employment
168,Central Valley,Total Wage and Salary,1000000,1485000
167,Central Valley,Total Private,5000000,1018300
135,Central Valley,Goods Producing,6000000,184600
158,Central Valley,Service Providing,7000000,1113000
152,Central Valley,Private Service Providing,8000000,833700
147,Central Valley,Mining and Logging,10000000,7600
166,Central Valley,Total Farm,11000000,187400
148,Central Valley,"Natural Resources, Mining and Constructi",15000000,76000
119,Central Valley,Construction,20000000,46600
161,Central Valley,Specialty Trade Contractors,20238000,21900
146,Central Valley,Manufacturing,30000000,108600
124,Central Valley,Durable Goods,31000000,31100
149,Central Valley,Nondurable Goods,32000000,68800
131,Central Valley,Food Manufacturing,32311000,38200
169,Central Valley,"Trade, Transportation and Utilities",40000000,304300
175,Central Valley,Wholesale Trade,41000000,44800
157,Central Valley,Retail Trade,42000000,156000
133,Central Valley,Food and Beverage Stores,42445000,19600
118,Central Valley,Clothing and Clothing Accessories Stores,42448000,6400
134,Central Valley,General Merchandise Stores,42452000,32900
122,Central Valley,Department Stores,42452200,2700
171,Central Valley,"Transportation, Warehousing and Utilitie",43000000,103500
170,Central Valley,Transportation and Warehousing,43400089,59600
172,Central Valley,Truck Transportation,43484000,7100
173,Central Valley,Warehousing and Storage,43493000,27000
139,Central Valley,Information,50000000,7100
130,Central Valley,Financial Activities,55000000,40400
129,Central Valley,Finance and Insurance,55520000,19900
121,Central Valley,Credit Intermediation and Related Activi,55522000,1900
140,Central Valley,Insurance Carriers and Related,55524000,4900
155,Central Valley,Real Estate and Rental and Leasing,55530000,7800
153,Central Valley,Professional and Business Services,60000000,115800
154,Central Valley,"Professional, Scientific and Technical S",60540000,20700
145,Central Valley,Management of Companies and Enterprises,60550000,5500
114,Central Valley,Administrative and Support and Waste Ser,60560000,57400
113,Central Valley,Administrative and Support Services,60561000,19200
174,Central Valley,Waste Management and Remediation Service,60562000,1300
126,Central Valley,Educational and Health Services,65000000,230600
125,Central Valley,Educational Services,65610000,10300
137,Central Valley,Health Care and Social Assistance,65620000,185500
115,Central Valley,Ambulatory Health Care Services,65621000,36000
138,Central Valley,Hospitals,65622000,22100
150,Central Valley,Nursing and Residential Care Facilities,65623000,8100
159,Central Valley,Social Assistance,65624000,26900
141,Central Valley,Leisure and Hospitality,70000000,101300
116,Central Valley,"Arts, Entertainment, and Recreation",70710000,2600
112,Central Valley,Accommodation and Food Service,70720000,70000
111,Central Valley,Accommodation,70721000,300
132,Central Valley,Food Services and Drinking Places,70722000,64800
156,Central Valley,Restaurants,70722500,32300
151,Central Valley,Other Services,80000000,34200
136,Central Valley,Government,90000000,279300
127,Central Valley,Federal Government,90910000,29300
128,Central Valley,Federal Government excluding Department of Def...,90912991,4400
123,Central Valley,Department of Defense,90919110,10100
162,Central Valley,State Government,90920000,44100
163,Central Valley,State Government Education,90921611,10100
164,Central Valley,State Government Excluding Education,90922000,9200
142,Central Valley,Local Government,90930000,205900
143,Central Valley,Local Government Education,90931611,100700
144,Central Valley,Local Government Excluding Education,90932000,77100
160,Central Valley,Special Districts plus Indian Tribes,90932994,18700
120,Central Valley,County,90939012,32200
117,Central Valley,City,90939022,14400
165,Central Valley,State and Local Government,90940000,250000

In [119]:
cv_2020['Current Employment'].sum() # before cutting down

8197100

In [126]:
cv_codes = [10000000, 11000000, 15000000, 20000000, 30000000, 41000000, 42000000, 43000000, 55000000, 60000000, 65000000, 70000000, 80000000, 90910000, 90920000, 90930000]

In [127]:
cv_test = cv_2020.loc[cv_2020['Series Code'].isin(cv_codes)]

In [128]:
cv_test['Current Employment'].sum()

1532100

Inland Empire

In [129]:
ie_2020

,Regions,Industry Title,Series Code,Current Employment
204,Inland Empire,Total Wage and Salary,1000000,1526500
186,Inland Empire,Goods Producing,6000000,201600
201,Inland Empire,Service Providing,7000000,1311600
194,Inland Empire,Mining and Logging,10000000,1200
203,Inland Empire,Total Farm,11000000,13300
179,Inland Empire,Construction,20000000,109500
193,Inland Empire,Manufacturing,30000000,90900
180,Inland Empire,Durable Goods,31000000,56800
195,Inland Empire,Nondurable Goods,32000000,34100
205,Inland Empire,"Trade, Transportation and Utilities",40000000,440200
207,Inland Empire,Wholesale Trade,41000000,64100
200,Inland Empire,Retail Trade,42000000,179800
206,Inland Empire,"Transportation, Warehousing and Utilitie",43000000,196300
189,Inland Empire,Information,50000000,8800
185,Inland Empire,Financial Activities,55000000,43400
184,Inland Empire,Finance and Insurance,55520000,24700
199,Inland Empire,Real Estate and Rental and Leasing,55530000,18700
197,Inland Empire,Professional and Business Services,60000000,158300
198,Inland Empire,"Professional, Scientific and Technical S",60540000,42900
192,Inland Empire,Management of Companies and Enterprises,60550000,8900
177,Inland Empire,Administrative and Support and Waste Ser,60560000,106500
182,Inland Empire,Educational and Health Services,65000000,252200
181,Inland Empire,Educational Services,65610000,18200
188,Inland Empire,Health Care and Social Assistance,65620000,234000
190,Inland Empire,Leisure and Hospitality,70000000,126900
178,Inland Empire,"Arts, Entertainment, and Recreation",70710000,11600
176,Inland Empire,Accommodation and Food Service,70720000,115300
196,Inland Empire,Other Services,80000000,36600
187,Inland Empire,Government,90000000,245200
183,Inland Empire,Federal Government,90910000,21600
202,Inland Empire,State Government,90920000,31300
191,Inland Empire,Local Government,90930000,192300

In [130]:
ie_2020['Current Employment'].sum() # before cutting down

5923300

In [131]:
ie_codes = [10000000, 11000000, 20000000, 31000000, 32000000, 41000000, 42000000, 43000000, 55000000, 60540000, 60550000, 60560000, 65610000, 65620000, 70710000, 70720000, 80000000, 90910000, 90920000, 90930000]

In [132]:
ie_test = ie_2020.loc[ie_2020['Series Code'].isin(ie_codes)]

In [133]:
ie_test['Current Employment'].sum()

1517700

Los Angeles

In [135]:
la_2020

,Regions,Industry Title,Series Code,Current Employment
374,Los Angeles,Total Wage and Salary,1000000,4106300
373,Los Angeles,Total Private,5000000,3551400
279,Los Angeles,Goods Producing,6000000,453300
358,Los Angeles,Service Providing,7000000,3648800
341,Los Angeles,Private Service Providing,8000000,3098100
308,Los Angeles,Mining and Logging,10000000,1600
372,Los Angeles,Total Farm,11000000,4200
317,Los Angeles,"Natural Resources, Mining and Constructi",15000000,146400
244,Los Angeles,Construction,20000000,144800
245,Los Angeles,Construction of Buildings,20236000,37800
352,Los Angeles,Residential Building Construction,20236100,23300
321,Los Angeles,Nonresidential Building Construction,20236200,14500
285,Los Angeles,Heavy and Civil Engineering Construction,20237000,15100
363,Los Angeles,Specialty Trade Contractors,20238000,91900
233,Los Angeles,Building Foundation and Exterior Contrac,20238100,19400
231,Los Angeles,Building Equipment Contractors,20238200,41500
232,Los Angeles,Building Finishing Contractors,20238300,21700
332,Los Angeles,Other Specialty Trade Contract,20238900,9300
305,Los Angeles,Manufacturing,30000000,306900
255,Los Angeles,Durable Goods,31000000,184900
339,Los Angeles,Primary Metal Manufacturing,31331000,5500
264,Los Angeles,Fabricated Metal Product Mfg,31332000,37800
301,Los Angeles,Machinery Manufacturing,31333000,11700
243,Los Angeles,Computer and Electronic Product Manufact,31334000,40000
260,Los Angeles,Electronic Instrument Manufacturing,31334500,25200
258,Los Angeles,Electrical Equipment and Appliance Manuf,31335000,6900
377,Los Angeles,Transportation Equipment Manufacturing,31336000,46200
216,Los Angeles,Aerospace Product and Parts Manufacturin,31336400,38800
274,Los Angeles,Furniture and Related Product Manufactur,31337000,11000
287,Los Angeles,Household and Institutional Furniture Ma,31337100,6400
310,Los Angeles,Miscellaneous Durable Goods Manufacturing,31339000,17000
320,Los Angeles,Nondurable Goods,32000000,122000
269,Los Angeles,Food Manufacturing,32311000,35900
250,Los Angeles,Dairy Product Manufacturing,32311500,3400
221,Los Angeles,Animal Slaughtering and Processing,32311600,4400
228,Los Angeles,Bakeries and Tortilla Manufacturing,32311800,13100
353,Los Angeles,ResidualTextile Mills,32313000,3600
222,Los Angeles,Apparel Manufacturing,32315000,20300
249,Los Angeles,Cut and Sew Apparel Manufacturing,32315200,19400
333,Los Angeles,Paper Manufacturing,32322000,6000
340,Los Angeles,Printing and Related Support Activities,32323000,9500
336,Los Angeles,Petroleum and Coal Products Manufacturin,32324000,5500
237,Los Angeles,Chemical Manufacturing,32325000,18900
337,Los Angeles,Pharmaceutical and Medicine Manufacturin,32325400,8000
338,Los Angeles,Plastics and Rubber Products Manufacturi,32326000,10900
375,Los Angeles,"Trade, Transportation and Utilities",40000000,823100
385,Los Angeles,Wholesale Trade,41000000,199100
306,Los Angeles,"Merchant Wholesalers, Durable Goods",41423000,93400
314,Los Angeles,Motor Vehicle and Motor Vehicle Parts Me,41423100,12000
343,Los Angeles,Professional and Commercial Equipment Me,41423400,14400
259,Los Angeles,Electrical and Electronic Goods Merchant,41423600,11000
302,Los Angeles,"Machinery, Equipment and Supplies Mercha",41423800,13800
311,Los Angeles,Miscellaneous Durable Goods Merchant Who,41423900,16200
307,Los Angeles,"Merchant Wholesalers, Nondurable Goods",41424000,95700
223,Los Angeles,"Apparel, Piece Gds & Notions Merch whole",41424300,22500
281,Los Angeles,Grocery & Related Products Merchant whol,41424400,35600
309,Los Angeles,Misc Nondurable Merchant Wholesalers,41424900,13400
384,Los Angeles,Wholesale Electronic Markets and Agents,41425000,10000
355,Los Angeles,Retail Trade,42000000,400300
315,Los Angeles,Motor Vehicle and Parts Dealer,42441000,40300
226,Los Angeles,Automobile Dealers,42441100,27300
330,Los Angeles,Other Motor Vehicle Dealers,42441200,1900
227,Los Angeles,"Automotive Parts, Accessories and Tire S",42441300,11100
273,Los Angeles,Furniture and Home Furnishings Stores,42442000,12800
261,Los Angeles,Electronics and Appliance Stores,42443000,15400
234,Los Angeles,Building Material and Garden Equipment S,42444000,26900
271,Los Angeles,Food and Beverage Stores,42445000,94600
282,Los Angeles,Grocery Stores,42445100,83400
284,Los Angeles,Health and Personal Care Stores,42446000,30900
276,Los Angeles,Gasoline Stations,42447000,11900
240,Los Angeles,Clothing and Clothing Accessories Stores,42448000,47900
365,Los Angeles,"Sporting Goods, Hobby, Book and Music St",42451000,11100
364,Los Angeles,"Sporting Goods, Hobby and Musical Instru",42451100,9900
229,Los Angeles,"Book, Periodical and Music Stores",42451200,1200
277,Los Angeles,General Merchandise Stores,42452000,69300
252,Los Angeles,Department Stores,42452200,20700
278,Los Angeles,"General Merchandise Stores, including Warehous...",42452300,48600
312,Los Angeles,Miscellaneous Store Retailers,42453000,20100
322,Los Angeles,Nonstore Retailers,42454000,19100
379,Los Angeles,"Transportation, Warehousing and Utilitie",43000000,223700
382,Los Angeles,Utilities,43220000,12700
378,Los Angeles,Transportation and Warehousing,43400089,211000
218,Los Angeles,Air Transportation,43481000,30400
381,Los Angeles,Truck Transportation,43484000,33100
376,Los Angeles,Transit and Ground Passenger Transportat,43485000,8000
370,Los Angeles,Support Activities for Transportation,43488000,54200
247,Los Angeles,Couriers and Messengers,43492000,60600
383,Los Angeles,Warehousing and Storage,43493000,19900
290,Los Angeles,Information,50000000,178300
345,Los Angeles,Publishing Industries (except Internet),50511000,19100
318,Los Angeles,"Newspaper, Periodical, Book and Director",50511100,6000
313,Los Angeles,Motion Picture and Sound Recording,50512000,96500
230,Los Angeles,Broadcasting (except Internet),50515000,21500
346,Los Angeles,Radio and Television Broadcasting,50515100,15400
236,Los Angeles,Cable and Other Subscription Programming,50515200,6100
371,Los Angeles,Telecommunications,50517000,15300
251,Los Angeles,"Data Processing, Hosting & Related Services",50518000,10000
268,Los Angeles,Financial Activities,55000000,210000
267,Los Angeles,Finance and Insurance,55520000,130900
248,Los Angeles,Credit Intermediation and Related Activi,55522000,57700
254,Los Angeles,Depository Credit Intermediation,55522100,39000
319,Los Angeles,Nondepository Credit Intermediation,55522200,11600
211,Los Angeles,Activities Related to Credit Intermediat,55522300,7100
357,Los Angeles,"Securities, Commodity Contracts and Inve",55523000,26100
292,Los Angeles,Insurance Carriers and Related,55524000,47100
291,Los Angeles,Insurance Carriers,55524100,19700
217,Los Angeles,"Agencies, Brokerages, and Other Insuranc",55524200,27400
348,Los Angeles,Real Estate and Rental and Leasing,55530000,79100
347,Los Angeles,Real Estate,55531000,63500
296,Los Angeles,Lessors of Real Estate,55531100,18000
328,Los Angeles,Offices of Real Estate Agents and Broker,55531200,13900
212,Los Angeles,Activities Related to Real Estate,55531300,31600
349,Los Angeles,Real Estate and Rental and Leasing - Residual,55539999,15600
342,Los Angeles,Professional and Business Services,60000000,594500
344,Los Angeles,"Professional, Scientific and Technical S",60540000,283800
294,Los Angeles,Legal Services,60541100,53800
210,Los Angeles,"Accounting, Tax Preparation and Bookkeep",60541200,41000
224,Los Angeles,"Architectural, Engineering and Related S",60541300,34700
242,Los Angeles,Computer Systems Design and Related Serv,60541500,36800
304,Los Angeles,"Management, Scientific and Technical Con",60541600,49600
356,Los Angeles,Scientific Research and Development Serv,60541700,19500
215,Los Angeles,Advertising and Related Services,60541800,24800
303,Los Angeles,Management of Companies and Enterprises,60550000,59200
214,Los Angeles,Administrative and Support and Waste Ser,60560000,251500
213,Los Angeles,Administrative and Support Services,60561000,239700
263,Los Angeles,Employment Services,60561300,88700
235,Los Angeles,Business Support Services,60561400,14100
380,Los Angeles,Travel Arrangement and Reservation Servi,60561500,5200
293,Los Angeles,Investigation and Security Services,60561600,52900
359,Los Angeles,Services to Buildings and Dwellings,60561700,47700
257,Los Angeles,Educational and Health Services,65000000,825900
256,Los Angeles,Educational Services,65610000,124100
262,Los Angeles,Elementary and Secondary Schools,65611100,29500
241,Los Angeles,"Colleges, Universities and Professional",65611300,71600
283,Los Angeles,Health Care and Social Assistance,65620000,701800
219,Los Angeles,Ambulatory Health Care Services,65621000,231700
327,Los Angeles,Offices of Physicians,65621100,61300
325,Los Angeles,Offices of Dentists,65621200,31400
326,Los Angeles,Offices of Other Health Practitioners,65621300,28500
286,Los Angeles,Hospitals,65622000,117200
324,Los Angeles,Nursing and Residential Care Facilities,65623000,82000
323,Los Angeles,Nursing Care Facilities,65623100,44200
360,Los Angeles,Social Assistance,65624000,270900
289,Los Angeles,Individual and Family Services,65624100,242600
238,Los Angeles,Child Day Care Services,65624400,14500
295,Los Angeles,Leisure and Hospitality,70000000,351300
225,Los Angeles,"Arts, Entertainment, and Recreation",70710000,58700
334,Los Angeles,"Performing Arts, Spectator Sports",70711000,34500
288,Los Angeles,"Independent Artists, Writers, and Perfor",70711500,11700
316,Los Angeles,"Museums, Historical Sites, and Similar I",70712000,3900
220,Los Angeles,"Amusement, Gambling, and Recreation",70713000,20300
275,Los Angeles,Gambling Industries,70713200,1700
329,Los Angeles,Other Amusement and Recreation,70713900,15500
209,Los Angeles,Accommodation and Food Service,70720000,292600
208,Los Angeles,Accommodation,70721000,25400
270,Los Angeles,Food Services and Drinking Places,70722000,267200
362,Los Angeles,Special Food Services,70722300,8300
354,Los Angeles,Restaurants,70722500,256800
272,Los Angeles,Full-Service Restaurants,70722511,96900
297,Los Angeles,Limited-Service Eating Places,70722590,159900
331,Los Angeles,Other Services,80000000,115000
351,Los Angeles,Repair and Maintenance,80811000,32300
335,Los Angeles,Personal and Laundry Services,80812000,32200
350,Los Angeles,"Religious, Grantmaking, Civic, Professio",80813000,50500
280,Los Angeles,Government,90000000,550700
265,Los Angeles,Federal Government,90910000,49400
266,Los Angeles,Federal Government excluding Department of Def...,90912991,45900
253,Los Angeles,Department of Defense,90919110,3500
366,Los Angeles,State Government,90920000,80000
367,Los Angeles,State Government Education,90921611,48900
368,Los Angeles,State Government Excluding Education,90922000,31100
298,Los Angeles,Local Government,90930000,421300
299,Los Angeles,Local Government Education,90931611,205600
300,Los Angeles,Local Government Excluding Education,90932000,215700
361,Los Angeles,Special Districts plus Indian Tribes,90932994,20200
246,Los Angeles,County,90939012,108000
239,Los Angeles,City,90939022,87500
369,Los Angeles,State and Local Government,90940000,501300

In [136]:
la_2020['Current Employment'].sum() # before cutting down

29612100

In [137]:
la_codes = [10000000, 11000000, 15000000, 20236000, 20237000, 20238000, 31000000, 32000000, 41000000, 42000000, 43220000, 43400089, 50000000, 55000000, 60540000, 60550000, 60560000, 65610000, 65620000, 70710000, 70720000, 80811000, 80812000, 80813000, 90910000, 90920000, 90930000]

In [138]:
la_test = la_2020.loc[la_2020['Series Code'].isin(la_codes)]

In [139]:
la_test['Current Employment'].sum()

4252700

Orange

In [140]:
oc_2020

,Regions,Industry Title,Series Code,Current Employment
475,Orange,Total Wage and Salary,1000000,1526800
474,Orange,Total Private,5000000,1370300
423,Orange,Goods Producing,6000000,250700
462,Orange,Service Providing,7000000,1274500
453,Orange,Private Service Providing,8000000,1119600
446,Orange,Mining and Logging,10000000,300
473,Orange,Total Farm,11000000,1600
448,Orange,"Natural Resources, Mining and Constructi",15000000,102900
402,Orange,Construction,20000000,102600
403,Orange,Construction of Buildings,20236000,21300
428,Orange,Heavy and Civil Engineering Construction,20237000,9700
466,Orange,Specialty Trade Contractors,20238000,71600
443,Orange,Manufacturing,30000000,147800
409,Orange,Durable Goods,31000000,109400
414,Orange,Fabricated Metal Product Mfg,31332000,20100
440,Orange,Machinery Manufacturing,31333000,7700
401,Orange,Computer and Electronic Product Manufact,31334000,32400
461,Orange,Semiconductor and Electronic Component M,31334400,13200
412,Orange,Electronic Instrument Manufacturing,31334500,12200
477,Orange,Transportation Equipment Manufacturing,31336000,12600
450,Orange,Nondurable Goods,32000000,38400
476,Orange,"Trade, Transportation and Utilities",40000000,253700
484,Orange,Wholesale Trade,41000000,75200
444,Orange,"Merchant Wholesalers, Durable Goods",41423000,46400
445,Orange,"Merchant Wholesalers, Nondurable Goods",41424000,23600
483,Orange,Wholesale Electronic Markets and Agents,41425000,5200
460,Orange,Retail Trade,42000000,146400
447,Orange,Motor Vehicle and Parts Dealer,42441000,16300
396,Orange,Building Material and Garden Equipment S,42444000,11700
420,Orange,Food and Beverage Stores,42445000,30000
425,Orange,Grocery Stores,42445100,27500
427,Orange,Health and Personal Care Stores,42446000,11200
398,Orange,Clothing and Clothing Accessories Stores,42448000,16200
467,Orange,"Sporting Goods, Hobby, Book and Music St",42451000,5000
422,Orange,General Merchandise Stores,42452000,28200
479,Orange,"Transportation, Warehousing and Utilitie",43000000,32100
480,Orange,Utilities,43220000,2900
478,Orange,Transportation and Warehousing,43400089,29200
405,Orange,Couriers and Messengers,43492000,9900
481,Orange,Warehousing and Storage,43493000,5600
430,Orange,Information,50000000,24100
456,Orange,Publishing Industries (except Internet),50511000,9900
472,Orange,Telecommunications,50517000,6200
418,Orange,Financial Activities,55000000,115400
417,Orange,Finance and Insurance,55520000,79400
406,Orange,Credit Intermediation and Related Activi,55522000,42500
408,Orange,Depository Credit Intermediation,55522100,17000
449,Orange,Nondepository Credit Intermediation,55522200,16600
432,Orange,Insurance Carriers and Related,55524000,23800
431,Orange,Insurance Carriers,55524100,8600
391,Orange,"Agencies, Brokerages, and Other Insuranc",55524200,15200
458,Orange,Real Estate and Rental and Leasing,55530000,36000
457,Orange,Real Estate,55531000,31600
454,Orange,Professional and Business Services,60000000,307100
455,Orange,"Professional, Scientific and Technical S",60540000,130600
434,Orange,Legal Services,60541100,16100
388,Orange,"Accounting, Tax Preparation and Bookkeep",60541200,15100
394,Orange,"Architectural, Engineering and Related S",60541300,25600
400,Orange,Computer Systems Design and Related Serv,60541500,23300
442,Orange,"Management, Scientific and Technical Con",60541600,27100
441,Orange,Management of Companies and Enterprises,60550000,36200
390,Orange,Administrative and Support and Waste Ser,60560000,140300
389,Orange,Administrative and Support Services,60561000,135400
413,Orange,Employment Services,60561300,68900
433,Orange,Investigation and Security Services,60561600,9500
463,Orange,Services to Buildings and Dwellings,60561700,33500
482,Orange,Waste Management and Remediation Service,60562000,4900
411,Orange,Educational and Health Services,65000000,227100
410,Orange,Educational Services,65610000,27700
399,Orange,"Colleges, Universities and Professional",65611300,7000
426,Orange,Health Care and Social Assistance,65620000,199400
392,Orange,Ambulatory Health Care Services,65621000,92100
429,Orange,Hospitals,65622000,32600
451,Orange,Nursing and Residential Care Facilities,65623000,27400
464,Orange,Social Assistance,65624000,47300
435,Orange,Leisure and Hospitality,70000000,149700
395,Orange,"Arts, Entertainment, and Recreation",70710000,28100
393,Orange,"Amusement, Gambling, and Recreation",70713000,22800
387,Orange,Accommodation and Food Service,70720000,121600
386,Orange,Accommodation,70721000,12700
419,Orange,Food Services and Drinking Places,70722000,108900
459,Orange,Restaurants,70722500,105000
421,Orange,Full-Service Restaurants,70722511,42800
436,Orange,Limited-Service Eating Places,70722590,62200
452,Orange,Other Services,80000000,42500
424,Orange,Government,90000000,154900
415,Orange,Federal Government,90910000,11300
416,Orange,Federal Government excluding Department of Def...,90912991,10200
407,Orange,Department of Defense,90919110,1100
468,Orange,State Government,90920000,33300
469,Orange,State Government Education,90921611,22100
470,Orange,State Government Excluding Education,90922000,11200
437,Orange,Local Government,90930000,110300
438,Orange,Local Government Education,90931611,70300
439,Orange,Local Government Excluding Education,90932000,40000
465,Orange,Special Districts plus Indian Tribes,90932994,7400
404,Orange,County,90939012,18200
397,Orange,City,90939022,14400
471,Orange,State and Local Government,90940000,143600

In [141]:
oc_2020['Current Employment'].sum() # before cutting down

10427100

In [142]:
oc_codes = [10000000, 11000000, 15000000, 20000000, 31000000, 32000000, 41000000, 42000000, 43220000, 43400089, 50000000, 55520000, 55530000, 60540000, 60550000, 60560000, 65610000, 65620000, 70710000, 70720000, 80000000, 90910000, 90920000, 90930000]

In [143]:
oc_test = oc_2020.loc[oc_2020['Series Code'].isin(oc_codes)]

In [144]:
oc_test['Current Employment'].sum()

1629700

Redwood Coast

In [145]:
rc_2020

,Regions,Industry Title,Series Code,Current Employment
510,Redwood Coast,Total Wage and Salary,1000000,84730
509,Redwood Coast,Total Private,5000000,59340
490,Redwood Coast,Goods Producing,6000000,8790
503,Redwood Coast,Service Providing,7000000,73370
500,Redwood Coast,Private Service Providing,8000000,50550
496,Redwood Coast,Mining and Logging,10000000,540
508,Redwood Coast,Total Farm,11000000,2580
497,Redwood Coast,"Natural Resources, Mining and Constructi",15000000,4280
485,Redwood Coast,Construction,20000000,3530
495,Redwood Coast,Manufacturing,30000000,4510
486,Redwood Coast,Durable Goods,31000000,2120
498,Redwood Coast,Nondurable Goods,32000000,2270
511,Redwood Coast,"Trade, Transportation and Utilities",40000000,16140
513,Redwood Coast,Wholesale Trade,41000000,1790
502,Redwood Coast,Retail Trade,42000000,11280
512,Redwood Coast,"Transportation, Warehousing and Utilitie",43000000,2050
492,Redwood Coast,Information,50000000,500
489,Redwood Coast,Financial Activities,55000000,2720
501,Redwood Coast,Professional and Business Services,60000000,5440
487,Redwood Coast,Educational and Health Services,65000000,15290
493,Redwood Coast,Leisure and Hospitality,70000000,7880
499,Redwood Coast,Other Services,80000000,2580
491,Redwood Coast,Government,90000000,22810
488,Redwood Coast,Federal Government,90910000,1240
504,Redwood Coast,State Government,90920000,5040
505,Redwood Coast,State Government Education,90921611,1800
506,Redwood Coast,State Government Excluding Education,90922000,1300
494,Redwood Coast,Local Government,90930000,16440
507,Redwood Coast,State and Local Government,90940000,21480

In [146]:
rc_2020['Current Employment'].sum() # before cutting down

432390

In [147]:
rc_codes = [10000000, 11000000, 15000000, 20000000, 31000000, 32000000, 40000000, 50000000, 55000000, 60000000, 65000000, 70000000, 80000000, 90910000, 90920000, 90930000]

In [148]:
rc_test = rc_2020.loc[rc_2020['Series Code'].isin(rc_codes)]

In [149]:
rc_test['Current Employment'].sum()

88590

Sacramento

In [150]:
sac_2020

,Regions,Industry Title,Series Code,Current Employment
541,Sacramento,Total Wage and Salary,1000000,1030200
523,Sacramento,Goods Producing,6000000,113900
538,Sacramento,Service Providing,7000000,905400
530,Sacramento,Mining and Logging,10000000,600
540,Sacramento,Total Farm,11000000,10900
531,Sacramento,"Natural Resources, Mining and Constructi",15000000,2600
517,Sacramento,Construction,20000000,73400
529,Sacramento,Manufacturing,30000000,37300
518,Sacramento,Durable Goods,31000000,22400
532,Sacramento,Nondurable Goods,32000000,12800
542,Sacramento,"Trade, Transportation and Utilities",40000000,178500
544,Sacramento,Wholesale Trade,41000000,27900
537,Sacramento,Retail Trade,42000000,108000
543,Sacramento,"Transportation, Warehousing and Utilitie",43000000,42600
525,Sacramento,Information,50000000,10000
522,Sacramento,Financial Activities,55000000,53300
521,Sacramento,Finance and Insurance,55520000,35500
536,Sacramento,Real Estate and Rental and Leasing,55530000,16400
534,Sacramento,Professional and Business Services,60000000,138100
535,Sacramento,"Professional, Scientific and Technical S",60540000,58900
528,Sacramento,Management of Companies and Enterprises,60550000,13300
515,Sacramento,Administrative and Support and Waste Ser,60560000,62700
519,Sacramento,Educational and Health Services,65000000,168900
526,Sacramento,Leisure and Hospitality,70000000,81400
516,Sacramento,"Arts, Entertainment, and Recreation",70710000,9800
514,Sacramento,Accommodation and Food Service,70720000,68400
533,Sacramento,Other Services,80000000,28800
524,Sacramento,Government,90000000,246400
520,Sacramento,Federal Government,90910000,16200
539,Sacramento,State Government,90920000,123100
527,Sacramento,Local Government,90930000,107100

In [151]:
sac_2020['Current Employment'].sum() # before cutting down

3804800

In [152]:
sac_codes = [10000000, 11000000, 15000000, 20000000, 30000000, 40000000, 50000000, 55000000, 60000000, 65000000, 70000000, 80000000, 90910000, 90920000, 90930000]

In [153]:
sac_test = sac_2020.loc[sac_2020['Series Code'].isin(sac_codes)]

In [154]:
sac_test['Current Employment'].sum()

1030200

San Diego-Imperial

In [155]:
sd_2020

,Regions,Industry Title,Series Code,Current Employment
635,San Diego-Imperial,Total Wage and Salary,1000000,1458200
634,San Diego-Imperial,Total Private,5000000,1185000
582,San Diego-Imperial,Goods Producing,6000000,204500
620,San Diego-Imperial,Service Providing,7000000,1234400
608,San Diego-Imperial,Private Service Providing,8000000,980500
600,San Diego-Imperial,Mining and Logging,10000000,300
633,San Diego-Imperial,Total Farm,11000000,19300
603,San Diego-Imperial,"Natural Resources, Mining and Constructi",15000000,89800
564,San Diego-Imperial,Construction,20000000,87800
565,San Diego-Imperial,Construction of Buildings,20236000,20600
587,San Diego-Imperial,Heavy and Civil Engineering Construction,20237000,8100
626,San Diego-Imperial,Specialty Trade Contractors,20238000,59100
557,San Diego-Imperial,Building Foundation and Exterior Contrac,20238100,12300
555,San Diego-Imperial,Building Equipment Contractors,20238200,23900
556,San Diego-Imperial,Building Finishing Contractors,20238300,16300
597,San Diego-Imperial,Manufacturing,30000000,114700
570,San Diego-Imperial,Durable Goods,31000000,85400
563,San Diego-Imperial,Computer and Electronic Product Manufact,31334000,30900
637,San Diego-Imperial,Transportation Equipment Manufacturing,31336000,20800
549,San Diego-Imperial,Aerospace Product and Parts Manufacturin,31336400,12200
622,San Diego-Imperial,Ship and Boat Building,31336600,7300
604,San Diego-Imperial,Nondurable Goods,32000000,29300
636,San Diego-Imperial,"Trade, Transportation and Utilities",40000000,232500
643,San Diego-Imperial,Wholesale Trade,41000000,41100
598,San Diego-Imperial,"Merchant Wholesalers, Durable Goods",41423000,21500
599,San Diego-Imperial,"Merchant Wholesalers, Nondurable Goods",41424000,15800
617,San Diego-Imperial,Retail Trade,42000000,152900
602,San Diego-Imperial,Motor Vehicle and Parts Dealer,42441000,15300
558,San Diego-Imperial,Building Material and Garden Equipment S,42444000,11800
579,San Diego-Imperial,Food and Beverage Stores,42445000,32600
584,San Diego-Imperial,Grocery Stores,42445100,28600
586,San Diego-Imperial,Health and Personal Care Stores,42446000,8400
561,San Diego-Imperial,Clothing and Clothing Accessories Stores,42448000,15800
560,San Diego-Imperial,Clothing Stores,42448100,12200
627,San Diego-Imperial,"Sporting Goods, Hobby, Book and Music St",42451000,7100
580,San Diego-Imperial,General Merchandise Stores,42452000,27100
568,San Diego-Imperial,Department Stores,42452200,9100
581,San Diego-Imperial,"General Merchandise Stores, including Warehous...",42452300,18000
601,San Diego-Imperial,Miscellaneous Store Retailers,42453000,7400
639,San Diego-Imperial,"Transportation, Warehousing and Utilitie",43000000,38500
640,San Diego-Imperial,Utilities,43220000,4800
638,San Diego-Imperial,Transportation and Warehousing,43400089,31500
641,San Diego-Imperial,Warehousing and Storage,43493000,2300
589,San Diego-Imperial,Information,50000000,22100
611,San Diego-Imperial,Publishing Industries (except Internet),50511000,7000
624,San Diego-Imperial,Software Publishers,50511200,5400
554,San Diego-Imperial,Broadcasting (except Internet),50515000,2600
632,San Diego-Imperial,Telecommunications,50517000,6300
577,San Diego-Imperial,Financial Activities,55000000,75100
576,San Diego-Imperial,Finance and Insurance,55520000,45600
567,San Diego-Imperial,Credit Intermediation and Related Activi,55522000,18700
619,San Diego-Imperial,"Securities, Commodity Contracts and Inve",55523000,9400
590,San Diego-Imperial,Insurance Carriers and Related,55524000,17500
613,San Diego-Imperial,Real Estate and Rental and Leasing,55530000,28400
612,San Diego-Imperial,Real Estate,55531000,23800
609,San Diego-Imperial,Professional and Business Services,60000000,256100
610,San Diego-Imperial,"Professional, Scientific and Technical S",60540000,146200
591,San Diego-Imperial,Legal Services,60541100,12800
552,San Diego-Imperial,"Architectural, Engineering and Related S",60541300,24700
618,San Diego-Imperial,Scientific Research and Development Serv,60541700,38200
596,San Diego-Imperial,Management of Companies and Enterprises,60550000,23800
548,San Diego-Imperial,Administrative and Support and Waste Ser,60560000,83400
547,San Diego-Imperial,Administrative and Support Services,60561000,79500
573,San Diego-Imperial,Employment Services,60561300,29200
621,San Diego-Imperial,Services to Buildings and Dwellings,60561700,24000
642,San Diego-Imperial,Waste Management and Remediation Service,60562000,3900
572,San Diego-Imperial,Educational and Health Services,65000000,220200
571,San Diego-Imperial,Educational Services,65610000,26000
562,San Diego-Imperial,"Colleges, Universities and Professional",65611300,9900
585,San Diego-Imperial,Health Care and Social Assistance,65620000,185800
550,San Diego-Imperial,Ambulatory Health Care Services,65621000,80800
588,San Diego-Imperial,Hospitals,65622000,23000
605,San Diego-Imperial,Nursing and Residential Care Facilities,65623000,27100
623,San Diego-Imperial,Social Assistance,65624000,54900
592,San Diego-Imperial,Leisure and Hospitality,70000000,133100
553,San Diego-Imperial,"Arts, Entertainment, and Recreation",70710000,14800
551,San Diego-Imperial,"Amusement, Gambling, and Recreation",70713000,9200
546,San Diego-Imperial,Accommodation and Food Service,70720000,115600
545,San Diego-Imperial,Accommodation,70721000,17500
578,San Diego-Imperial,Food Services and Drinking Places,70722000,98100
616,San Diego-Imperial,Restaurants,70722500,93900
606,San Diego-Imperial,Other Services,80000000,41400
615,San Diego-Imperial,Repair and Maintenance,80811000,11000
607,San Diego-Imperial,Personal and Laundry Services,80812000,11700
614,San Diego-Imperial,"Religious, Grantmaking, Civic, Professio",80813000,17900
583,San Diego-Imperial,Government,90000000,253900
574,San Diego-Imperial,Federal Government,90910000,50500
575,San Diego-Imperial,Federal Government excluding Department of Def...,90912991,23800
569,San Diego-Imperial,Department of Defense,90919110,24500
628,San Diego-Imperial,State Government,90920000,52200
629,San Diego-Imperial,State Government Education,90921611,32100
630,San Diego-Imperial,State Government Excluding Education,90922000,17300
593,San Diego-Imperial,Local Government,90930000,151200
594,San Diego-Imperial,Local Government Education,90931611,71900
595,San Diego-Imperial,Local Government Excluding Education,90932000,73400
625,San Diego-Imperial,Special Districts plus Indian Tribes,90932994,29700
566,San Diego-Imperial,County,90939012,20900
559,San Diego-Imperial,City,90939022,18600
631,San Diego-Imperial,State and Local Government,90940000,203400

In [156]:
sd_2020['Current Employment'].sum() # before cutting down

9634000

In [157]:
sd_codes = [10000000, 11000000, 15000000, 20236000, 20237000, 20238000, 31000000, 32000000, 41000000, 42000000, 43220000, 43400089, 43493000, 50000000, 55000000, 60540000, 60550000, 60560000, 65000000, 70000000, 80000000, 90910000, 90920000, 90930000]

In [158]:
sd_test = sd_2020.loc[sd_2020['Series Code'].isin(sd_codes)]

In [159]:
sd_test['Current Employment'].sum()

1543700

Shasta / Cascades

In [160]:
shas_2020

,Regions,Industry Title,Series Code,Current Employment
674,Shasta / Cascades,Total Wage and Salary,1000000,208040
673,Shasta / Cascades,Total Private,5000000,153100
651,Shasta / Cascades,Goods Producing,6000000,22650
667,Shasta / Cascades,Service Providing,7000000,174300
663,Shasta / Cascades,Private Service Providing,8000000,129250
664,Shasta / Cascades,Private Service Providing - Residual,8999999,490
659,Shasta / Cascades,Mining and Logging,10000000,250
672,Shasta / Cascades,Total Farm,11000000,11110
660,Shasta / Cascades,"Natural Resources, Mining and Constructi",15000000,11200
645,Shasta / Cascades,Construction,20000000,1380
658,Shasta / Cascades,Manufacturing,30000000,11450
646,Shasta / Cascades,Durable Goods,31000000,2800
661,Shasta / Cascades,Nondurable Goods,32000000,2050
675,Shasta / Cascades,"Trade, Transportation and Utilities",40000000,40590
677,Shasta / Cascades,Wholesale Trade,41000000,5490
666,Shasta / Cascades,Retail Trade,42000000,27160
676,Shasta / Cascades,"Transportation, Warehousing and Utilitie",43000000,7580
653,Shasta / Cascades,Information,50000000,1490
650,Shasta / Cascades,Financial Activities,55000000,7070
649,Shasta / Cascades,Finance and Insurance,55520000,1700
665,Shasta / Cascades,Professional and Business Services,60000000,13650
647,Shasta / Cascades,Educational and Health Services,65000000,44960
654,Shasta / Cascades,Leisure and Hospitality,70000000,16070
644,Shasta / Cascades,Accommodation and Food Service,70720000,4300
662,Shasta / Cascades,Other Services,80000000,6070
652,Shasta / Cascades,Government,90000000,43840
648,Shasta / Cascades,Federal Government,90910000,3360
669,Shasta / Cascades,State Government,90920000,6860
670,Shasta / Cascades,State Government Education,90921611,2800
655,Shasta / Cascades,Local Government,90930000,33600
656,Shasta / Cascades,Local Government Education,90931611,5600
657,Shasta / Cascades,Local Government Excluding Education,90932000,9100
668,Shasta / Cascades,Special Districts plus Indian Tribes,90932994,2700
671,Shasta / Cascades,State and Local Government,90940000,40460

In [161]:
shas_2020['Current Employment'].sum() # before cutting down

1052520

In [162]:
shas_codes = [8999999, 10000000, 11000000, 15000000, 20000000, 30000000, 41000000, 42000000, 43000000, 50000000, 55000000, 60000000, 65000000, 70000000, 80000000, 90910000, 90920000, 90930000]

In [163]:
shas_test = shas_2020.loc[shas_2020['Series Code'].isin(shas_codes)]

In [164]:
shas_test['Current Employment'].sum()

209240

Sierra Nevada

In [165]:
sn_2020

,Regions,Industry Title,Series Code,Current Employment
702,Sierra Nevada,Total Wage and Salary,1000000,105950
701,Sierra Nevada,Total Private,5000000,69850
683,Sierra Nevada,Goods Producing,6000000,11030
697,Sierra Nevada,Service Providing,7000000,93510
693,Sierra Nevada,Private Service Providing,8000000,53730
694,Sierra Nevada,Private Service Providing - Residual,8999999,500
689,Sierra Nevada,Mining and Logging,10000000,500
700,Sierra Nevada,Total Farm,11000000,1430
690,Sierra Nevada,"Natural Resources, Mining and Constructi",15000000,6960
678,Sierra Nevada,Construction,20000000,2100
688,Sierra Nevada,Manufacturing,30000000,4030
679,Sierra Nevada,Durable Goods,31000000,1110
691,Sierra Nevada,Nondurable Goods,32000000,1010
703,Sierra Nevada,"Trade, Transportation and Utilities",40000000,15530
705,Sierra Nevada,Wholesale Trade,41000000,980
696,Sierra Nevada,Retail Trade,42000000,12330
704,Sierra Nevada,"Transportation, Warehousing and Utilitie",43000000,1910
685,Sierra Nevada,Information,50000000,650
682,Sierra Nevada,Financial Activities,55000000,3020
695,Sierra Nevada,Professional and Business Services,60000000,5710
680,Sierra Nevada,Educational and Health Services,65000000,13930
686,Sierra Nevada,Leisure and Hospitality,70000000,15700
692,Sierra Nevada,Other Services,80000000,3250
684,Sierra Nevada,Government,90000000,34670
681,Sierra Nevada,Federal Government,90910000,4340
698,Sierra Nevada,State Government,90920000,7160
687,Sierra Nevada,Local Government,90930000,23190
699,Sierra Nevada,State and Local Government,90940000,30330

In [166]:
sn_2020['Current Employment'].sum() # before cutting down

524410

In [167]:
sn_codes = [8999999, 10000000, 11000000, 15000000, 20000000, 30000000, 41000000, 42000000, 43000000, 50000000, 55000000, 60000000, 65000000, 70000000, 80000000, 90910000, 90920000, 90930000]

In [168]:
sn_test = sn_2020.loc[sn_2020['Series Code'].isin(sn_codes)]

In [169]:
sn_test['Current Employment'].sum()

107690

concatenate all regions

In [170]:
test_2020 = [ba_test, cc_test, cv_test, ie_test, la_test, oc_test, rc_test, sac_test, sd_test, shas_test, sn_test]

In [172]:
concat_test = pd.concat(test_2020)

In [173]:
concat_test

,Regions,Industry Title,Series Code,Current Employment
30,Bay Area,Mining and Logging,10000000,800
47,Bay Area,Total Farm,11000000,14600
31,Bay Area,"Natural Resources, Mining and Constructi",15000000,152200
7,Bay Area,Construction,20000000,83300
29,Bay Area,Manufacturing,30000000,353700
52,Bay Area,Wholesale Trade,41000000,104700
39,Bay Area,Retail Trade,42000000,314700
51,Bay Area,"Transportation, Warehousing and Utilitie",43000000,121000
23,Bay Area,Information,50000000,246400
36,Bay Area,"Professional, Scientific and Technical S",60540000,483800
28,Bay Area,Management of Companies and Enterprises,60550000,64700
2,Bay Area,Administrative and Support and Waste Ser,60560000,187300
12,Bay Area,Educational and Health Services,65000000,594700
24,Bay Area,Leisure and Hospitality,70000000,245700
33,Bay Area,Other Services,80000000,97300
13,Bay Area,Federal Government,90910000,46700
43,Bay Area,State Government,90920000,96600
25,Bay Area,Local Government,90930000,308500
88,Central Coast,Mining and Logging,10000000,1800
104,Central Coast,Total Farm,11000000,93100
89,Central Coast,"Natural Resources, Mining and Constructi",15000000,46400
62,Central Coast,Construction,20000000,33500
87,Central Coast,Manufacturing,30000000,59000
110,Central Coast,Wholesale Trade,41000000,29800
96,Central Coast,Retail Trade,42000000,98400
109,Central Coast,"Transportation, Warehousing and Utilitie",43000000,20200
73,Central Coast,Financial Activities,55000000,33400
93,Central Coast,Professional and Business Services,60000000,116000
68,Central Coast,Educational and Health Services,65000000,131900
82,Central Coast,Leisure and Hospitality,70000000,87600
91,Central Coast,Other Services,80000000,25100
70,Central Coast,Federal Government,90910000,19000
100,Central Coast,State Government,90920000,35500
83,Central Coast,Local Government,90930000,101300
147,Central Valley,Mining and Logging,10000000,7600
166,Central Valley,Total Farm,11000000,187400
148,Central Valley,"Natural Resources, Mining and Constructi",15000000,76000
119,Central Valley,Construction,20000000,46600
146,Central Valley,Manufacturing,30000000,108600
175,Central Valley,Wholesale Trade,41000000,44800
157,Central Valley,Retail Trade,42000000,156000
171,Central Valley,"Transportation, Warehousing and Utilitie",43000000,103500
130,Central Valley,Financial Activities,55000000,40400
153,Central Valley,Professional and Business Services,60000000,115800
126,Central Valley,Educational and Health Services,65000000,230600
141,Central Valley,Leisure and Hospitality,70000000,101300
151,Central Valley,Other Services,80000000,34200
127,Central Valley,Federal Government,90910000,29300
162,Central Valley,State Government,90920000,44100
142,Central Valley,Local Government,90930000,205900
194,Inland Empire,Mining and Logging,10000000,1200
203,Inland Empire,Total Farm,11000000,13300
179,Inland Empire,Construction,20000000,109500
180,Inland Empire,Durable Goods,31000000,56800
195,Inland Empire,Nondurable Goods,32000000,34100
207,Inland Empire,Wholesale Trade,41000000,64100
200,Inland Empire,Retail Trade,42000000,179800
206,Inland Empire,"Transportation, Warehousing and Utilitie",43000000,196300
185,Inland Empire,Financial Activities,55000000,43400
198,Inland Empire,"Professional, Scientific and Technical S",60540000,42900
192,Inland Empire,Management of Companies and Enterprises,60550000,8900
177,Inland Empire,Administrative and Support and Waste Ser,60560000,106500
181,Inland Empire,Educational Services,65610000,18200
188,Inland Empire,Health Care and Social Assistance,65620000,234000
178,Inland Empire,"Arts, Entertainment, and Recreation",70710000,11600
176,Inland Empire,Accommodation and Food Service,70720000,115300
196,Inland Empire,Other Services,80000000,36600
183,Inland Empire,Federal Government,90910000,21600
202,Inland Empire,State Government,90920000,31300
191,Inland Empire,Local Government,90930000,192300
308,Los Angeles,Mining and Logging,10000000,1600
372,Los Angeles,Total Farm,11000000,4200
317,Los Angeles,"Natural Resources, Mining and Constructi",15000000,146400
245,Los Angeles,Construction of Buildings,20236000,37800
285,Los Angeles,Heavy and Civil Engineering Construction,20237000,15100
363,Los Angeles,Specialty Trade Contractors,20238000,91900
255,Los Angeles,Durable Goods,31000000,184900
320,Los Angeles,Nondurable Goods,32000000,122000
385,Los Angeles,Wholesale Trade,41000000,199100
355,Los Angeles,Retail Trade,42000000,400300
382,Los Angeles,Utilities,43220000,12700
378,Los Angeles,Transportation and Warehousing,43400089,211000
290,Los Angeles,Information,50000000,178300
268,Los Angeles,Financial Activities,55000000,210000
344,Los Angeles,"Professional, Scientific and Technical S",60540000,283800
303,Los Angeles,Management of Companies and Enterprises,60550000,59200
214,Los Angeles,Administrative and Support and Waste Ser,60560000,251500
256,Los Angeles,Educational Services,65610000,124100
283,Los Angeles,Health Care and Social Assistance,65620000,701800
225,Los Angeles,"Arts, Entertainment, and Recreation",70710000,58700
209,Los Angeles,Accommodation and Food Service,70720000,292600
351,Los Angeles,Repair and Maintenance,80811000,32300
335,Los Angeles,Personal and Laundry Services,80812000,32200
350,Los Angeles,"Religious, Grantmaking, Civic, Professio",80813000,50500
265,Los Angeles,Federal Government,90910000,49400
366,Los Angeles,State Government,90920000,80000
298,Los Angeles,Local Government,90930000,421300
446,Orange,Mining and Logging,10000000,300
473,Orange,Total Farm,11000000,1600
448,Orange,"Natural Resources, Mining and Constructi",15000000,102900
402,Orange,Construction,20000000,102600
409,Orange,Durable Goods,31000000,109400
450,Orange,Nondurable Goods,32000000,38400
484,Orange,Wholesale Trade,41000000,75200
460,Orange,Retail Trade,42000000,146400
480,Orange,Utilities,43220000,2900
478,Orange,Transportation and Warehousing,43400089,29200
430,Orange,Information,50000000,24100
417,Orange,Finance and Insurance,55520000,79400
458,Orange,Real Estate and Rental and Leasing,55530000,36000
455,Orange,"Professional, Scientific and Technical S",60540000,130600
441,Orange,Management of Companies and Enterprises,60550000,36200
390,Orange,Administrative and Support and Waste Ser,60560000,140300
410,Orange,Educational Services,65610000,27700
426,Orange,Health Care and Social Assistance,65620000,199400
395,Orange,"Arts, Entertainment, and Recreation",70710000,28100
387,Orange,Accommodation and Food Service,70720000,121600
452,Orange,Other Services,80000000,42500
415,Orange,Federal Government,90910000,11300
468,Orange,State Government,90920000,33300
437,Orange,Local Government,90930000,110300
496,Redwood Coast,Mining and Logging,10000000,540
508,Redwood Coast,Total Farm,11000000,2580
497,Redwood Coast,"Natural Resources, Mining and Constructi",15000000,4280
485,Redwood Coast,Construction,20000000,3530
486,Redwood Coast,Durable Goods,31000000,2120
498,Redwood Coast,Nondurable Goods,32000000,2270
511,Redwood Coast,"Trade, Transportation and Utilities",40000000,16140
492,Redwood Coast,Information,50000000,500
489,Redwood Coast,Financial Activities,55000000,2720
501,Redwood Coast,Professional and Business Services,60000000,5440
487,Redwood Coast,Educational and Health Services,65000000,15290
493,Redwood Coast,Leisure and Hospitality,70000000,7880
499,Redwood Coast,Other Services,80000000,2580
488,Redwood Coast,Federal Government,90910000,1240
504,Redwood Coast,State Government,90920000,5040
494,Redwood Coast,Local Government,90930000,16440
530,Sacramento,Mining and Logging,10000000,600
540,Sacramento,Total Farm,11000000,10900
531,Sacramento,"Natural Resources, Mining and Constructi",15000000,2600
517,Sacramento,Construction,20000000,73400
529,Sacramento,Manufacturing,30000000,37300
542,Sacramento,"Trade, Transportation and Utilities",40000000,178500
525,Sacramento,Information,50000000,10000
522,Sacramento,Financial Activities,55000000,53300
534,Sacramento,Professional and Business Services,60000000,138100
519,Sacramento,Educational and Health Services,65000000,168900
526,Sacramento,Leisure and Hospitality,70000000,81400
533,Sacramento,Other Services,80000000,28800
520,Sacramento,Federal Government,90910000,16200
539,Sacramento,State Government,90920000,123100
527,Sacramento,Local Government,90930000,107100
600,San Diego-Imperial,Mining and Logging,10000000,300
633,San Diego-Imperial,Total Farm,11000000,19300
603,San Diego-Imperial,"Natural Resources, Mining and Constructi",15000000,89800
565,San Diego-Imperial,Construction of Buildings,20236000,20600
587,San Diego-Imperial,Heavy and Civil Engineering Construction,20237000,8100
626,San Diego-Imperial,Specialty Trade Contractors,20238000,59100
570,San Diego-Imperial,Durable Goods,31000000,85400
604,San Diego-Imperial,Nondurable Goods,32000000,29300
643,San Diego-Imperial,Wholesale Trade,41000000,41100
617,San Diego-Imperial,Retail Trade,42000000,152900
640,San Diego-Imperial,Utilities,43220000,4800
638,San Diego-Imperial,Transportation and Warehousing,43400089,31500
641,San Diego-Imperial,Warehousing and Storage,43493000,2300
589,San Diego-Imperial,Information,50000000,22100
577,San Diego-Imperial,Financial Activities,55000000,75100
610,San Diego-Imperial,"Professional, Scientific and Technical S",60540000,146200
596,San Diego-Imperial,Management of Companies and Enterprises,60550000,23800
548,San Diego-Imperial,Administrative and Support and Waste Ser,60560000,83400
572,San Diego-Imperial,Educational and Health Services,65000000,220200
592,San Diego-Imperial,Leisure and Hospitality,70000000,133100
606,San Diego-Imperial,Other Services,80000000,41400
574,San Diego-Imperial,Federal Government,90910000,50500
628,San Diego-Imperial,State Government,90920000,52200
593,San Diego-Imperial,Local Government,90930000,151200
664,Shasta / Cascades,Private Service Providing - Residual,8999999,490
659,Shasta / Cascades,Mining and Logging,10000000,250
672,Shasta / Cascades,Total Farm,11000000,11110
660,Shasta / Cascades,"Natural Resources, Mining and Constructi",15000000,11200
645,Shasta / Cascades,Construction,20000000,1380
658,Shasta / Cascades,Manufacturing,30000000,11450
677,Shasta / Cascades,Wholesale Trade,41000000,5490
666,Shasta / Cascades,Retail Trade,42000000,27160
676,Shasta / Cascades,"Transportation, Warehousing and Utilitie",43000000,7580
653,Shasta / Cascades,Information,50000000,1490
650,Shasta / Cascades,Financial Activities,55000000,7070
665,Shasta / Cascades,Professional and Business Services,60000000,13650
647,Shasta / Cascades,Educational and Health Services,65000000,44960
654,Shasta / Cascades,Leisure and Hospitality,70000000,16070
662,Shasta / Cascades,Other Services,80000000,6070
648,Shasta / Cascades,Federal Government,90910000,3360
669,Shasta / Cascades,State Government,90920000,6860
655,Shasta / Cascades,Local Government,90930000,33600
694,Sierra Nevada,Private Service Providing - Residual,8999999,500
689,Sierra Nevada,Mining and Logging,10000000,500
700,Sierra Nevada,Total Farm,11000000,1430
690,Sierra Nevada,"Natural Resources, Mining and Constructi",15000000,6960
678,Sierra Nevada,Construction,20000000,2100
688,Sierra Nevada,Manufacturing,30000000,4030
705,Sierra Nevada,Wholesale Trade,41000000,980
696,Sierra Nevada,Retail Trade,42000000,12330
704,Sierra Nevada,"Transportation, Warehousing and Utilitie",43000000,1910
685,Sierra Nevada,Information,50000000,650
682,Sierra Nevada,Financial Activities,55000000,3020
695,Sierra Nevada,Professional and Business Services,60000000,5710
680,Sierra Nevada,Educational and Health Services,65000000,13930
686,Sierra Nevada,Leisure and Hospitality,70000000,15700
692,Sierra Nevada,Other Services,80000000,3250
681,Sierra Nevada,Federal Government,90910000,4340
698,Sierra Nevada,State Government,90920000,7160
687,Sierra Nevada,Local Government,90930000,23190

In [174]:
concat_test['Current Employment'].sum()

16360320

#### Dictionary to store region specific series codes

In [175]:
region_series_codes = {'Bay Area':[10000000, 11000000, 15000000, 20000000, 30000000, 41000000, 42000000, 43000000, 50000000, 60540000, 60550000, 60560000, 65000000, 70000000, 80000000, 90910000, 90920000, 90930000],
                       'Central Coast':[10000000, 11000000, 15000000, 20000000, 30000000, 41000000, 42000000, 43000000, 55000000, 60000000, 65000000, 70000000, 80000000, 90910000, 90920000, 90930000],
                       'Central Valley':[10000000, 11000000, 15000000, 20000000, 30000000, 41000000, 42000000, 43000000, 55000000, 60000000, 65000000, 70000000, 80000000, 90910000, 90920000, 90930000],
                       'Inland Empire':[10000000, 11000000, 20000000, 31000000, 32000000, 41000000, 42000000, 43000000, 55000000, 60540000, 60550000, 60560000, 65610000, 65620000, 70710000, 70720000, 80000000, 90910000, 90920000, 90930000],
                       'Los Angeles':[10000000, 11000000, 15000000, 20236000, 20237000, 20238000, 31000000, 32000000, 41000000, 42000000, 43220000, 43400089, 50000000, 55000000, 60540000, 60550000, 60560000, 65610000, 65620000, 70710000, 70720000, 80811000, 80812000, 80813000, 90910000, 90920000, 90930000],
                       'Orange':[10000000, 11000000, 15000000, 20000000, 31000000, 32000000, 41000000, 42000000, 43220000, 43400089, 50000000, 55520000, 55530000, 60540000, 60550000, 60560000, 65610000, 65620000, 70710000, 70720000, 80000000, 90910000, 90920000, 90930000],
                       'Redwood Coast':[10000000, 11000000, 15000000, 20000000, 31000000, 32000000, 40000000, 50000000, 55000000, 60000000, 65000000, 70000000, 80000000, 90910000, 90920000, 90930000],
                       'Sacramento':[10000000, 11000000, 15000000, 20000000, 30000000, 40000000, 50000000, 55000000, 60000000, 65000000, 70000000, 80000000, 90910000, 90920000, 90930000],
                       'San Diego-Imperial':[10000000, 11000000, 15000000, 20236000, 20237000, 20238000, 31000000, 32000000, 41000000, 42000000, 43220000, 43400089, 43493000, 50000000, 55000000, 60540000, 60550000, 60560000, 65000000, 70000000, 80000000, 90910000, 90920000, 90930000],
                       'Shasta / Cascades':[8999999, 10000000, 11000000, 15000000, 20000000, 30000000, 41000000, 42000000, 43000000, 50000000, 55000000, 60000000, 65000000, 70000000, 80000000, 90910000, 90920000, 90930000],
                       'Sierra Nevada':[8999999, 10000000, 11000000, 15000000, 20000000, 30000000, 41000000, 42000000, 43000000, 50000000, 55000000, 60000000, 65000000, 70000000, 80000000, 90910000, 90920000, 90930000]
}

In [200]:
region_series_codes['Bay Area']

[10000000,
 11000000,
 15000000,
 20000000,
 30000000,
 41000000,
 42000000,
 43000000,
 50000000,
 60540000,
 60550000,
 60560000,
 65000000,
 70000000,
 80000000,
 90910000,
 90920000,
 90930000]

### Filtering full_edd using dictionary

In [195]:
full_edd_regions = full_edd_regions.loc[full_edd_regions['Year'] >= 2014]

In [196]:
sorted(full_edd_regions['Year'].unique())

[2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021]

In [197]:
len(full_edd_regions)

193086

In [198]:
def filter_edd(edd, regions_dict):
    # separate dataframes
    ba = edd.loc[edd['Regions'] == 'Bay Area']
    cc = edd.loc[edd['Regions'] == 'Central Coast']
    cv = edd.loc[edd['Regions'] == 'Central Valley']
    ie = edd.loc[edd['Regions'] == 'Inland Empire']
    la = edd.loc[edd['Regions'] == 'Los Angeles']
    oc = edd.loc[edd['Regions'] == 'Orange']
    rc = edd.loc[edd['Regions'] == 'Redwood Coast']
    sac = edd.loc[edd['Regions'] == 'Sacramento']
    sd = edd.loc[edd['Regions'] == 'San Diego-Imperial']
    shas = edd.loc[edd['Regions'] == 'Shasta / Cascades']
    sn = edd.loc[edd['Regions'] == 'Sierra Nevada']
    
    # filter out series codes
    ba = ba.loc[ba['Series Code'].isin(regions_dict['Bay Area'])]
    cc = cc.loc[cc['Series Code'].isin(regions_dict['Central Coast'])]
    cv = cv.loc[cv['Series Code'].isin(regions_dict['Central Valley'])]
    ie = ie.loc[ie['Series Code'].isin(regions_dict['Inland Empire'])]
    la = la.loc[la['Series Code'].isin(regions_dict['Los Angeles'])]
    oc = oc.loc[oc['Series Code'].isin(regions_dict['Orange'])]
    rc = rc.loc[rc['Series Code'].isin(regions_dict['Redwood Coast'])]
    sac = sac.loc[sac['Series Code'].isin(regions_dict['Sacramento'])]
    sd = sd.loc[sd['Series Code'].isin(regions_dict['San Diego-Imperial'])]
    shas = shas.loc[shas['Series Code'].isin(regions_dict['Shasta / Cascades'])]
    sn = sn.loc[sn['Series Code'].isin(regions_dict['Sierra Nevada'])]
    
    dfs = [ba, cc, cv, ie, la, oc, rc, sac, sd, shas, sn]
    final_edd = pd.concat(dfs)
    
    return final_edd

Big function - works best on a year by year basis

In [204]:
edd_2020 = full_edd_regions.loc[full_edd_regions['Year'] == 2020]
edd_2019 = full_edd_regions.loc[full_edd_regions['Year'] == 2019]
edd_2018 = full_edd_regions.loc[full_edd_regions['Year'] == 2018]
edd_2017 = full_edd_regions.loc[full_edd_regions['Year'] == 2017]
edd_2016 = full_edd_regions.loc[full_edd_regions['Year'] == 2016]
edd_2015 = full_edd_regions.loc[full_edd_regions['Year'] == 2015]
edd_2014 = full_edd_regions.loc[full_edd_regions['Year'] == 2014]

In [205]:
edd_2020 = filter_edd(edd_2020, region_series_codes)
edd_2019 = filter_edd(edd_2019, region_series_codes)
edd_2018 = filter_edd(edd_2018, region_series_codes)
edd_2017 = filter_edd(edd_2017, region_series_codes)
edd_2016 = filter_edd(edd_2016, region_series_codes)
edd_2015 = filter_edd(edd_2015, region_series_codes)
edd_2014 = filter_edd(edd_2014, region_series_codes)

In [207]:
filtered_edd = pd.concat([edd_2020, edd_2019, edd_2018, edd_2017, edd_2016, edd_2015, edd_2014])

In [208]:
len(filtered_edd)

74172

CREATE CROSSWALK

In [209]:
filtered_edd.head()

,Area Type,Area Name,Year,Month,Date,Series Code,Industry Title,Seasonally Adjusted,Current Employment,FIPS,COUNTYFIP,County,Rural/Urban,Regions
2304,County,Alameda,2020,January,01/01/2020,50000000,Information,N,20900,6001,1,Alameda,Urban,Bay Area
2305,County,Alameda,2020,January,01/01/2020,42000000,Retail Trade,N,69400,6001,1,Alameda,Urban,Bay Area
2307,County,Alameda,2020,January,01/01/2020,80000000,Other Services,N,27400,6001,1,Alameda,Urban,Bay Area
2309,County,Alameda,2020,January,01/01/2020,70000000,Leisure and Hospitality,N,76000,6001,1,Alameda,Urban,Bay Area
2312,County,Alameda,2020,January,01/01/2020,65000000,Educational and Health Services,N,127300,6001,1,Alameda,Urban,Bay Area

In [211]:
ind_tuples = set()
for row in filtered_edd.iterrows():
    ind_tuples.add((row[1][5], row[1][6]))
ind_tuples = sorted(ind_tuples)

In [213]:
series_codes = []
inds = []
for tup in ind_tuples:
    series_codes.append(tup[0])
    inds.append(tup[1])
crosswalk_cols = {'Series Code':series_codes, 'Industry':inds}
crosswalk_df = pd.DataFrame(crosswalk_cols)

In [216]:
crosswalk_df = crosswalk_df.reset_index()
crosswalk_df = crosswalk_df.rename(columns={'index':'Crosswalk Value'})

In [217]:
crosswalk_df

    Crosswalk Value  Series Code                                  Industry
0                 0      8999999      Private Service Providing - Residual
1                 1     10000000                        Mining and Logging
2                 2     11000000                                Total Farm
3                 3     15000000  Natural Resources, Mining and Constructi
4                 4     20000000                              Construction
5                 5     20236000                 Construction of Buildings
6                 6     20237000  Heavy and Civil Engineering Construction
7                 7     20238000               Specialty Trade Contractors
8                 8     30000000                             Manufacturing
9                 9     31000000                             Durable Goods
10               10     32000000                          Nondurable Goods
11               11     40000000       Trade, Transportation and Utilities
12               12     41000000                           Wholesale Trade
13               13     42000000                              Retail Trade
14               14     43000000  Transportation, Warehousing and Utilitie
15               15     43220000                                 Utilities
16               16     43400089            Transportation and Warehousing
17               17     43493000                   Warehousing and Storage
18               18     50000000                               Information
19               19     55000000                      Financial Activities
20               20     55520000                     Finance and Insurance
21               21     55530000        Real Estate and Rental and Leasing
22               22     60000000        Professional and Business Services
23               23     60540000  Professional, Scientific and Technical S
24               24     60550000   Management of Companies and Enterprises
25               25     60560000  Administrative and Support and Waste Ser
26               26     65000000           Educational and Health Services
27               27     65610000                      Educational Services
28               28     65620000         Health Care and Social Assistance
29               29     70000000                   Leisure and Hospitality
30               30     70710000       Arts, Entertainment, and Recreation
31               31     70720000            Accommodation and Food Service
32               32     80000000                            Other Services
33               33     80811000                    Repair and Maintenance
34               34     80812000             Personal and Laundry Services
35               35     80813000  Religious, Grantmaking, Civic, Professio
36               36     90910000                        Federal Government
37               37     90920000                          State Government
38               38     90930000                          Local Government

In [218]:
crosswalk_df.to_csv('edd_to_ipums_crosswalk.csv', index=False)

### More old testing

make series code column as str for parsing/testing

In [17]:
edd_test_2020['series_code_str'] = edd_test_2020['Series Code'].astype(str)

List all industries and their series codes to individually pick out the best ones

In [18]:
ind_tuples = set()
for row in full_edd.iterrows():
    ind_tuples.add((row[1][5], row[1][6]))

In [19]:
sorted(ind_tuples)

[(0, 'Total Nonfarm'),
 (1000000, 'Total Wage and Salary'),
 (5000000, 'Total Private'),
 (6000000, 'Goods Producing'),
 (7000000, 'Service Providing'),
 (8000000, 'Private Service Providing'),
 (8999999, 'Private Service Providing - Residual'),
 (10000000, 'Mining and Logging'),
 (10113300, 'Logging'),
 (10210000, 'Mining'),
 (10211000, 'Oil & Gas Extraction'),
 (10212000, 'Mining, except Oil & Gas'),
 (10213000, 'Support Activities for Mining'),
 (11000000, 'Total Farm'),
 (15000000, 'Natural Resources, Mining and Constructi'),
 (20000000, 'Construction'),
 (20236000, 'Construction of Buildings'),
 (20236100, 'Residential Building Construction'),
 (20236200, 'Nonresidential Building Construction'),
 (20237000, 'Heavy and Civil Engineering Construction'),
 (20237100, 'Utility System Const.'),
 (20237200, 'L& Subdivision'),
 (20237300, 'Highway, Street, and Bridge Const'),
 (20237900, 'Other Heavy & Civil Engineer'),
 (20238000, 'Specialty Trade Contractors'),
 (20238100, 'Building Foundation and Exterior Contrac'),
 (20238200, 'Building Equipment Contractors'),
 (20238300, 'Building Finishing Contractors'),
 (20238900, 'Other Specialty Trade Contract'),
 (30000000, 'Manufacturing'),
 (31000000, 'Durable Goods'),
 (31321000, 'Wood Product Manufacturing'),
 (31321900, 'Other Wood Product Mfg.'),
 (31327000, 'Nonmetallic Mineral Product Mfg.'),
 (31331000, 'Primary Metal Manufacturing'),
 (31332000, 'Fabricated Metal Product Mfg'),
 (31332300, 'Architectural & Structural Metals Mfg.'),
 (31332700, 'Machine Shops & Threaded Product Mfg.'),
 (31332900, 'Other Fabricated Metal Product Mfg.'),
 (31333000, 'Machinery Manufacturing'),
 (31333200, 'Industrial Machinery Manufacturing'),
 (31333300, 'Commercial and Service Industry Manufact'),
 (31333500, 'Metalworking Machinery Mfg.'),
 (31333900, 'ResidualOther General Purpose Machinery'),
 (31334000, 'Computer and Electronic Product Manufact'),
 (31334100, 'Computer and Peripheral Equipment Manufa'),
 (31334111, 'Electronic Computer Manufacturing'),
 (31334200, 'Communications Equipment Manufacturing'),
 (31334400, 'Semiconductor and Electronic Component M'),
 (31334412, 'Bare Printed Circuit Board Manufacturing'),
 (31334413, 'Semiconductor and Related Devices Manufa'),
 (31334500, 'Electronic Instrument Manufacturing'),
 (31335000, 'Electrical Equipment and Appliance Manuf'),
 (31336000, 'Transportation Equipment Manufacturing'),
 (31336100, 'Motor Vehicle Mfg.'),
 (31336400, 'Aerospace Product and Parts Manufacturin'),
 (31336600, 'Ship and Boat Building'),
 (31337000, 'Furniture and Related Product Manufactur'),
 (31337100, 'Household and Institutional Furniture Ma'),
 (31339000, 'Miscellaneous Durable Goods Manufacturing'),
 (31339100, 'Medical Equipment & Supplies Mfg.'),
 (31339900, 'Other Miscellaneous Durable Goods Mfg.'),
 (32000000, 'Nondurable Goods'),
 (32311000, 'Food Manufacturing'),
 (32311400, 'Fruit & Vegetable Preserving & Specialty'),
 (32311500, 'Dairy Product Manufacturing'),
 (32311600, 'Animal Slaughtering and Processing'),
 (32311800, 'Bakeries and Tortilla Manufacturing'),
 (32311900, 'Other Food Mfg.'),
 (32312000, 'Beverage and Tobacco Product Mfg'),
 (32313000, 'ResidualTextile Mills'),
 (32314000, 'Textile Product Mills'),
 (32315000, 'Apparel Manufacturing'),
 (32315100, 'Apparel Knitting Mills'),
 (32315200, 'Cut and Sew Apparel Manufacturing'),
 (32322000, 'Paper Manufacturing'),
 (32322200, 'Converted Paper Product Mfg.'),
 (32323000, 'Printing and Related Support Activities'),
 (32324000, 'Petroleum and Coal Products Manufacturin'),
 (32325000, 'Chemical Manufacturing'),
 (32325400, 'Pharmaceutical and Medicine Manufacturin'),
 (32325600, 'Soap, Cleaning Compound & Toiletry Mfg.'),
 (32326000, 'Plastics and Rubber Products Manufacturi'),
 (40000000, 'Trade, Transportation and Utilities'),
 (41000000, 'Wholesale Trade'),
 (41423000, 'Merchant Wholesalers, Durable Goods'),
 (41423100, 'Motor Vehicle and Motor Vehicle Parts Me'),
 (41423200, 'Furniture & Home Furnish Merch whole'),
 (41423300, 'Lumber & Other Const. Mat Merch whole'),
 (41423400, 'Professional and Commercial Equipment Me'),
 (41423600, 'Electrical and Electronic Goods Merchant'),
 (41423700, 'Hdwr, Plumb & Heating Merchant whole'),
 (41423800, 'Machinery, Equipment and Supplies Mercha'),
 (41423900, 'Miscellaneous Durable Goods Merchant Who'),
 (41424000, 'Merchant Wholesalers, Nondurable Goods'),
 (41424100, 'Paper & Paper Products Merchant whole'),
 (41424300, 'Apparel, Piece Gds & Notions Merch whole'),
 (41424400, 'Grocery & Related Products Merchant whol'),
 (41424600, 'Chemical & Allied Products Merchant whol'),
 (41424900, 'Misc Nondurable Merchant Wholesalers'),
 (41425000, 'Wholesale Electronic Markets and Agents'),
 (42000000, 'Retail Trade'),
 (42441000, 'Motor Vehicle and Parts Dealer'),
 (42441100, 'Automobile Dealers'),
 (42441200, 'Other Motor Vehicle Dealers'),
 (42441300, 'Automotive Parts, Accessories and Tire S'),
 (42442000, 'Furniture and Home Furnishings Stores'),
 (42442100, 'Furniture Stores'),
 (42442200, 'Home Furnishings Stores'),
 (42443000, 'Electronics and Appliance Stores'),
 (42444000, 'Building Material and Garden Equipment S'),
 (42444100, 'Building Material and Supplies Dealers'),
 (42445000, 'Food and Beverage Stores'),
 (42445100, 'Grocery Stores'),
 (42445200, 'Specialty Food Stores'),
 (42445300, 'Beer, Wine, & Liquor Stores'),
 (42446000, 'Health and Personal Care Stores'),
 (42447000, 'Gasoline Stations'),
 (42448000, 'Clothing and Clothing Accessories Stores'),
 (42448100, 'Clothing Stores'),
 (42448300, 'Jewelry, Luggage & Leather Gds Stores'),
 (42451000, 'Sporting Goods, Hobby, Book and Music St'),
 (42451100, 'Sporting Goods, Hobby and Musical Instru'),
 (42451200, 'Book, Periodical and Music Stores'),
 (42452000, 'General Merchandise Stores'),
 (42452200, 'Department Stores'),
 (42452300,
  'General Merchandise Stores, including Warehouse Clubs and Supercenters'),
 (42453000, 'Miscellaneous Store Retailers'),
 (42453200, 'Office Supplies, Stationery & Gift Store'),
 (42453300, 'Used Merch&ise Stores'),
 (42453900, 'Other Miscellaneous Store Retailers'),
 (42454000, 'Nonstore Retailers'),
 (42454100, 'Electronic Shopping & Mail-Order'),
 (43000000, 'Transportation, Warehousing and Utilitie'),
 (43220000, 'Utilities'),
 (43221100, 'Electric Power Gen, Trans & Distribution'),
 (43221200, 'Natural Gas Distribution'),
 (43400089, 'Transportation and Warehousing'),
 (43481000, 'Air Transportation'),
 (43481100, 'Scheduled Air transp.'),
 (43484000, 'Truck Transportation'),
 (43484100, 'General Freight Trucking'),
 (43484200, 'Specialized Freight Trucking'),
 (43485000, 'Transit and Ground Passenger Transportat'),
 (43488000, 'Support Activities for Transportation'),
 (43488300, 'Support Activities for Water transp.'),
 (43488400, 'Support Activities for Road transp.'),
 (43488500, 'Freight transp. Arrangement'),
 (43492000, 'Couriers and Messengers'),
 (43493000, 'Warehousing and Storage'),
 (50000000, 'Information'),
 (50511000, 'Publishing Industries (except Internet)'),
 (50511100, 'Newspaper, Periodical, Book and Director'),
 (50511200, 'Software Publishers'),
 (50512000, 'Motion Picture and Sound Recording'),
 (50512100, 'Motion Picture & Video Industries'),
 (50512110, 'Motion Picture & Video Production'),
 (50515000, 'Broadcasting (except Internet)'),
 (50515100, 'Radio and Television Broadcasting'),
 (50515200, 'Cable and Other Subscription Programming'),
 (50517000, 'Telecommunications'),
 (50517311, 'Wired Telecommunications Carriers'),
 (50518000, 'Data Processing, Hosting & Related Services'),
 (50519000, 'Other Information Serv.'),
 (55000000, 'Financial Activities'),
 (55520000, 'Finance and Insurance'),
 (55522000, 'Credit Intermediation and Related Activi'),
 (55522100, 'Depository Credit Intermediation'),
 (55522200, 'Nondepository Credit Intermediation'),
 (55522300, 'Activities Related to Credit Intermediat'),
 (55523000, 'Securities, Commodity Contracts and Inve'),
 (55523100, 'Securities & Commodity Contracts'),
 (55523900, 'Other Financial Investment Activities'),
 (55524000, 'Insurance Carriers and Related'),
 (55524100, 'Insurance Carriers'),
 (55524200, 'Agencies, Brokerages, and Other Insuranc'),
 (55530000, 'Real Estate and Rental and Leasing'),
 (55531000, 'Real Estate'),
 (55531100, 'Lessors of Real Estate'),
 (55531200, 'Offices of Real Estate Agents and Broker'),
 (55531300, 'Activities Related to Real Estate'),
 (55532000, 'Rental and Leasing Services'),
 (55532100, 'Automotive Equipment Rental and Leasing'),
 (55532200, 'Consumer Goods Rental'),
 (55532300, 'General Rental Centers'),
 (55532400, 'Comm & Industrial Mach Rental & Leasing'),
 (55539999, 'Real Estate and Rental and Leasing - Residual'),
 (60000000, 'Professional and Business Services'),
 (60540000, 'Professional, Scientific and Technical S'),
 (60541100, 'Legal Services'),
 (60541200, 'Accounting, Tax Preparation and Bookkeep'),
 (60541300, 'Architectural, Engineering and Related S'),
 (60541400, 'Specialized Design Services'),
 (60541500, 'Computer Systems Design and Related Serv'),
 (60541600, 'Management, Scientific and Technical Con'),
 (60541700, 'Scientific Research and Development Serv'),
 (60541800, 'Advertising and Related Services'),
 (60541900, 'Other Professional, Scientific and Techn'),
 (60550000, 'Management of Companies and Enterprises'),
 (60560000, 'Administrative and Support and Waste Ser'),
 (60561000, 'Administrative and Support Services'),
 (60561100, 'Office Administrative Services'),
 (60561200, 'Facilities Support Serv.'),
 (60561300, 'Employment Services'),
 (60561400, 'Business Support Services'),
 (60561500, 'Travel Arrangement and Reservation Servi'),
 (60561600, 'Investigation and Security Services'),
 (60561700, 'Services to Buildings and Dwellings'),
 (60561900, 'ResidualOther Support Services'),
 (60562000, 'Waste Management and Remediation Service'),
 (65000000, 'Educational and Health Services'),
 (65610000, 'Educational Services'),
 (65611100, 'Elementary and Secondary Schools'),
 (65611200, 'Junior Colleges'),
 (65611300, 'Colleges, Universities and Professional'),
 (65611600, 'Other Schools & Instruction'),
 (65620000, 'Health Care and Social Assistance'),
 (65621000, 'Ambulatory Health Care Services'),
 (65621100, 'Offices of Physicians'),
 (65621200, 'Offices of Dentists'),
 (65621300, 'Offices of Other Health Practitioners'),
 (65621400, 'Outpatient Care Centers'),
 (65621500, 'Medical & Diagnostic Laboratories'),
 (65621600, 'Home Health Care Serv.'),
 (65621900, 'Other Ambulatory Health Care Serv.'),
 (65622000, 'Hospitals'),
 (65622100, 'General Medical & Surgical Hosp.s'),
 (65622200, 'Psychiatric & Substance Abuse Hosp'),
 (65622300, 'Specialty (not Psych, Sub Abuse) Hosp.'),
 (65623000, 'Nursing and Residential Care Facilities'),
 (65623100, 'Nursing Care Facilities'),
 (65623200, 'Residential Intellectual & Developmental Disability'),
 (65623300, 'Comm Care Facilities for the Elderly'),
 (65623900, 'Other Residential Care Facilities'),
 (65624000, 'Social Assistance'),
 (65624100, 'Individual and Family Services'),
 (65624200, 'Community Food & Housing, & Emergency &'),
 (65624300, 'Vocational Rehabilitation Services'),
 (65624400, 'Child Day Care Services'),
 (70000000, 'Leisure and Hospitality'),
 (70710000, 'Arts, Entertainment, and Recreation'),
 (70711000, 'Performing Arts, Spectator Sports'),
 (70711100, 'Performing Arts Companies'),
 (70711200, 'Spectator Sports'),
 (70711500, 'Independent Artists, Writers, and Perfor'),
 (70712000, 'Museums, Historical Sites, and Similar I'),
 (70713000, 'Amusement, Gambling, and Recreation'),
 (70713100, 'Amusement Parks and Arcades'),
 (70713200, 'Gambling Industries'),
 (70713900, 'Other Amusement and Recreation'),
 (70720000, 'Accommodation and Food Service'),
 (70721000, 'Accommodation'),
 (70722000, 'Food Services and Drinking Places'),
 (70722300, 'Special Food Services'),
 (70722400, 'Drinking Places (Alcoholic Beverages)'),
 (70722500, 'Restaurants'),
 (70722511, 'Full-Service Restaurants'),
 (70722590, 'Limited-Service Eating Places'),
 (80000000, 'Other Services'),
 (80811000, 'Repair and Maintenance'),
 (80811100, 'Auto Repair & Maintenance'),
 (80811300, 'Commercial & Industrial Machinery'),
 (80811400, 'Personal & Household Goods Repair'),
 (80812000, 'Personal and Laundry Services'),
 (80812100, 'Personal Care Serv.'),
 (80812300, 'Drycleaning & Laundry Serv.'),
 (80812900, 'Other Personal Services'),
 (80813000, 'Religious, Grantmaking, Civic, Professio'),
 (80813100, 'Religious Organizations'),
 (80813200, 'Grantmaking & Giving Serv.'),
 (80813300, 'Social Advocacy Organizations'),
 (80813400, 'Civic & Social Organizations'),
 (80813900, 'Bus,Labor, Political & Other like Org.'),
 (90000000, 'Government'),
 (90910000, 'Federal Government'),
 (90912991, 'Federal Government excluding Department of Defense'),
 (90919110, 'Department of Defense'),
 (90920000, 'State Government'),
 (90921611, 'State Government Education'),
 (90922000, 'State Government Excluding Education'),
 (90930000, 'Local Government'),
 (90931150, 'Indian Tribes'),
 (90931611, 'Local Government Education'),
 (90932000, 'Local Government Excluding Education'),
 (90932994, 'Special Districts plus Indian Tribes'),
 (90939012, 'County'),
 (90939022, 'City'),
 (90939032, 'Special Districts'),
 (90940000, 'State and Local Government')]

In [20]:
selected_codes = [8999999, 11000000, 10000000, 15000000, 20236000, 20237000, 20238000, 31321000, 31327000, 31331000, 31332000, 31333000, 31334000, 31335000, 31336000, 31337000, 31339000,
32311000, 32312000, 32313000, 32314000, 32315000, 32322000, 32323000, 32324000, 32325000, 32326000, 41423000, 41424000, 41425000, 42441000, 42442000, 42443000, 42444000, 42445000, 42446000, 42447000, 42448000,
42451000, 42452000, 42453000, 42454000, 43220000, 43400089, 50511100, 50511200, 50512000, 50515100, 50515200, 50517000, 50518000, 50519000, 55522000, 55523000, 55524000, 55531000, 55532000,
60541100, 60541200, 60541300, 60541400, 60541500, 60541600, 60541700, 60541800, 60541900, 60550000, 60561000, 60562000, 65610000, 65621000, 65622000, 65623000, 65624000, 70711000, 70712000, 70713000, 70721000,
70722000, 80811000, 80812000, 80813000, 90910000, 90920000, 90930000]

In [21]:
# replaced all industries under "durable goods manufacturing" and "nondurable goods manufacturing" with these broader titles
selected_codes_2 = [8999999, 11000000, 10000000, 15000000, 20236000, 20237000, 20238000, 31000000,
32000000, 41423000, 41424000, 41425000, 42441000, 42442000, 42443000, 42444000, 42445000, 42446000, 42447000, 42448000,
42451000, 42452000, 42453000, 42454000, 43220000, 43400089, 50511100, 50511200, 50512000, 50515100, 50515200, 50517000, 50518000, 50519000, 55522000, 55523000, 55524000, 55531000, 55532000,
60541100, 60541200, 60541300, 60541400, 60541500, 60541600, 60541700, 60541800, 60541900, 60550000, 60561000, 60562000, 65610000, 65621000, 65622000, 65623000, 65624000, 70711000, 70712000, 70713000, 70721000,
70722000, 80811000, 80812000, 80813000, 90910000, 90920000, 90930000]

comments
- feeling unsure about codes starting with a 1
- used spreadsheet for reference - highlighting and going off initial scratch work

In [22]:
# for spot testing
full_edd[full_edd['Series Code'] == 8999999]

,Area Type,Area Name,Year,Month,Date,Series Code,Industry Title,Seasonally Adjusted,Current Employment
134,County,Colusa,2014,January,01/01/2014,8999999,Private Service Providing - Residual,N,330
792,County,Mariposa,2014,January,01/01/2014,8999999,Private Service Providing - Residual,N,220
876,County,Modoc,2014,January,01/01/2014,8999999,Private Service Providing - Residual,N,200
892,County,Mono,2014,January,01/01/2014,8999999,Private Service Providing - Residual,N,240
1922,County,Trinity,2014,January,01/01/2014,8999999,Private Service Providing - Residual,N,130
...,...,...,...,...,...,...,...,...,...
1312343,County,Trinity,1997,April,04/01/1997,8999999,Private Service Providing - Residual,N,250
1314607,County,Colusa,1997,May,05/01/1997,8999999,Private Service Providing - Residual,N,230
1315262,County,Mariposa,1997,May,05/01/1997,8999999,Private Service Providing - Residual,N,160
1315347,County,Modoc,1997,May,05/01/1997,8999999,Private Service Providing - Residual,N,230
1315362,County,Mono,1997,May,05/01/1997,8999999,Private Service Providing - Residual,N,260

In [91]:
edd_test = edd_test_2020.loc[edd_test_2020['Series Code'].isin(selected_codes_2)]

In [24]:
edd_test['Current Employment'].sum()

10576230

In [25]:
edd_test

,index,Area Type,Area Name,Year,Month,Date,Series Code,Industry Title,Seasonally Adjusted,Current Employment,series_code_str
0,335911,County,Yuba,2020,December,12/01/2020,11000000,Total Farm,N,400,11000000
4,336604,County,Alameda,2020,December,12/01/2020,32000000,Nondurable Goods,N,20900,32000000
11,336611,County,Alameda,2020,December,12/01/2020,11000000,Total Farm,N,600,11000000
14,336614,County,Alameda,2020,December,12/01/2020,90910000,Federal Government,N,8800,90910000
15,336615,County,Alameda,2020,December,12/01/2020,90930000,Local Government,N,71900,90930000
...,...,...,...,...,...,...,...,...,...,...,...
1996,338678,County,Yolo,2020,December,12/01/2020,60550000,Management of Companies and Enterprises,N,1100,60550000
1999,338681,County,Yuba,2020,December,12/01/2020,90920000,State Government,N,1000,90920000
2007,338690,County,Yuba,2020,December,12/01/2020,15000000,"Natural Resources, Mining and Constructi",N,1200,15000000
2008,338691,County,Yuba,2020,December,12/01/2020,90910000,Federal Government,N,1400,90910000
2011,338694,County,Yuba,2020,December,12/01/2020,90930000,Local Government,N,4900,90930000

### old testing - a more pythonic way, but less useful

**testing:** cut down series codes based on the number of zeros at the end and comparing employment counts

test 1: Ends with 2 zeros or less

In [26]:
parsed_codes = []
for i in range(len(edd_test_2020['series_code_str'])):
    parsed_codes.append(edd_test_2020['series_code_str'][i][-3:])
edd_test_2020['last3'] = parsed_codes

In [27]:
edd_test1 = edd_test_2020.loc[edd_test_2020['last3'] != '000']

In [28]:
edd_test1

,index,Area Type,Area Name,Year,Month,Date,Series Code,Industry Title,Seasonally Adjusted,Current Employment,series_code_str,last3
72,336677,County,Butte,2020,December,12/01/2020,90932994,Special Districts plus Indian Tribes,N,1400,90932994,994
88,336693,County,Butte,2020,December,12/01/2020,90921611,State Government Education,N,2800,90921611,611
126,336733,County,Colusa,2020,December,12/01/2020,8999999,Private Service Providing - Residual,N,200,8999999,999
230,336842,County,Fresno,2020,December,12/01/2020,90932994,Special Districts plus Indian Tribes,N,2500,90932994,994
242,336854,County,Fresno,2020,December,12/01/2020,90939022,City,N,5600,90939022,022
...,...,...,...,...,...,...,...,...,...,...,...,...
1946,338627,County,Ventura,2020,December,12/01/2020,90919110,Department of Defense,N,6000,90919110,110
1953,338634,County,Ventura,2020,December,12/01/2020,90921611,State Government Education,N,1300,90921611,611
1959,338640,County,Ventura,2020,December,12/01/2020,90931611,Local Government Education,N,19100,90931611,611
1960,338641,County,Ventura,2020,December,12/01/2020,90939012,County,N,8900,90939012,012
1967,338648,County,Ventura,2020,December,12/01/2020,43400089,Transportation and Warehousing,N,5500,43400089,089

In [29]:
edd_test1['Current Employment'].sum()

4918090

test 2: Ends with 3 zeros or less

In [30]:
parsed_codes = []
for i in range(len(edd_test_2020['series_code_str'])):
    parsed_codes.append(edd_test_2020['series_code_str'][i][-4:])
edd_test_2020['last4'] = parsed_codes

In [31]:
edd_test2 = edd_test_2020.loc[edd_test_2020['last4'] != '0000']

In [32]:
edd_test2

,index,Area Type,Area Name,Year,Month,Date,Series Code,Industry Title,Seasonally Adjusted,Current Employment,series_code_str,last3,last4
72,336677,County,Butte,2020,December,12/01/2020,90932994,Special Districts plus Indian Tribes,N,1400,90932994,994,2994
83,336688,County,Butte,2020,December,12/01/2020,90932000,Local Government Excluding Education,N,4400,90932000,000,2000
88,336693,County,Butte,2020,December,12/01/2020,90921611,State Government Education,N,2800,90921611,611,1611
126,336733,County,Colusa,2020,December,12/01/2020,8999999,Private Service Providing - Residual,N,200,8999999,999,9999
229,336841,County,Fresno,2020,December,12/01/2020,32311000,Food Manufacturing,N,12000,32311000,000,1000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1960,338641,County,Ventura,2020,December,12/01/2020,90939012,County,N,8900,90939012,012,9012
1961,338642,County,Ventura,2020,December,12/01/2020,60561000,Administrative and Support Services,N,17100,60561000,000,1000
1966,338647,County,Ventura,2020,December,12/01/2020,42452000,General Merchandise Stores,N,5900,42452000,000,2000
1967,338648,County,Ventura,2020,December,12/01/2020,43400089,Transportation and Warehousing,N,5500,43400089,089,0089
1968,338649,County,Ventura,2020,December,12/01/2020,20238000,Specialty Trade Contractors,N,10900,20238000,000,8000

In [33]:
edd_test2['Current Employment'].sum()

10848490

test 3: Ends with 4 zeros or less

In [34]:
parsed_codes = []
for i in range(len(edd_test_2020['series_code_str'])):
    parsed_codes.append(edd_test_2020['series_code_str'][i][-5:])
edd_test_2020['last5'] = parsed_codes

In [35]:
edd_test3 = edd_test_2020.loc[edd_test_2020['last5'] != '00000']

In [36]:
edd_test3

,index,Area Type,Area Name,Year,Month,Date,Series Code,Industry Title,Seasonally Adjusted,Current Employment,series_code_str,last3,last4,last5
3,336603,County,Alameda,2020,December,12/01/2020,60560000,Administrative and Support and Waste Ser,N,38000,60560000,000,0000,60000
5,336605,County,Alameda,2020,December,12/01/2020,65620000,Health Care and Social Assistance,N,109400,65620000,000,0000,20000
9,336609,County,Alameda,2020,December,12/01/2020,70710000,"Arts, Entertainment, and Recreation",N,4900,70710000,000,0000,10000
14,336614,County,Alameda,2020,December,12/01/2020,90910000,Federal Government,N,8800,90910000,000,0000,10000
15,336615,County,Alameda,2020,December,12/01/2020,90930000,Local Government,N,71900,90930000,000,0000,30000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1996,338678,County,Yolo,2020,December,12/01/2020,60550000,Management of Companies and Enterprises,N,1100,60550000,000,0000,50000
1998,338680,County,Yolo,2020,December,12/01/2020,55520000,Finance and Insurance,N,1000,55520000,000,0000,20000
1999,338681,County,Yuba,2020,December,12/01/2020,90920000,State Government,N,1000,90920000,000,0000,20000
2008,338691,County,Yuba,2020,December,12/01/2020,90910000,Federal Government,N,1400,90910000,000,0000,10000
2011,338694,County,Yuba,2020,December,12/01/2020,90930000,Local Government,N,4900,90930000,000,0000,30000

In [37]:
edd_test3['Current Employment'].sum()

21279490

In [38]:
# edd_test3['Industry Title'].unique()

test 4: custom list of codes

In [39]:
custom_codes = [8999999, 15000000, 20236100, 20236200, 20237000, 20238100, 20238200, 20238300, 20238900, 31331000, 31332000, 31333000, 
31334400, 31334500, 31335000, 31336400, 31336600, 31337000, 31339000, 32311500, 32311600, 32311800, 32312000, 32313000, 32315000, 32322000, 32323000, 32324000, 32325000, 32326000, 41423100, 41423400,41423600,41423800,41423900, 41424300,41424400,41424900,41425000, 42441100,42441200, 42441300, 42442000, 42443000, 42444000, 42445000, 42446000, 42447000, 42448000, 42451000,42452000,42453000,42454000, 43220000,43400089,43481000,43484000,43485000,43488000,43492000,43493000, 50511000,50512000,50515000,50517000,50518000, 55522100,55522200,55522300,55523000,55524100,55524200, 55531100,55531200,55531300,55539999,60541100,60541200,60541300,60541500,60541600,60541700,60541800,60550000, 60561300,60561400,60561500,60561600,60561700,60562000,65611100,
 65611300,65621100,65621200, 65621300, 65622000, 65623000, 65624100, 65624400, 70711000, 70712000, 70713000, 70721000, 70722000, 80811000, 80812000,
 80813000, 90910000, 90920000, 90930000, 90940000]

In [40]:
edd_test4 = edd_test_2020.loc[edd_test_2020['Series Code'].isin(custom_codes)]

In [41]:
edd_test4

,index,Area Type,Area Name,Year,Month,Date,Series Code,Industry Title,Seasonally Adjusted,Current Employment,series_code_str,last3,last4,last5
14,336614,County,Alameda,2020,December,12/01/2020,90910000,Federal Government,N,8800,90910000,000,0000,10000
15,336615,County,Alameda,2020,December,12/01/2020,90930000,Local Government,N,71900,90930000,000,0000,30000
16,336616,County,Alameda,2020,December,12/01/2020,15000000,"Natural Resources, Mining and Constructi",N,48000,15000000,000,0000,00000
26,336626,County,Alameda,2020,December,12/01/2020,60550000,Management of Companies and Enterprises,N,15500,60550000,000,0000,50000
27,336627,County,Alameda,2020,December,12/01/2020,90920000,State Government,N,37000,90920000,000,0000,20000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1996,338678,County,Yolo,2020,December,12/01/2020,60550000,Management of Companies and Enterprises,N,1100,60550000,000,0000,50000
1999,338681,County,Yuba,2020,December,12/01/2020,90920000,State Government,N,1000,90920000,000,0000,20000
2007,338690,County,Yuba,2020,December,12/01/2020,15000000,"Natural Resources, Mining and Constructi",N,1200,15000000,000,0000,00000
2008,338691,County,Yuba,2020,December,12/01/2020,90910000,Federal Government,N,1400,90910000,000,0000,10000
2011,338694,County,Yuba,2020,December,12/01/2020,90930000,Local Government,N,4900,90930000,000,0000,30000

In [42]:
edd_test4['Current Employment'].sum()

9789830

test 5: take test 3 and cut specific industries that I know clearly overlap

In [43]:
# to exclude
ind_to_cut = ['State and Local Government', 'Local Government Excluding Education', 'State Government Education', 'Local Government Education', 'City', 'County', 'Department of Defense', 'Federal Government excluding Department of Defense', 'State Government Excluding Education', 'Residential Building Construction', 'Nonresidential Building Construction',
             'Arts, Entertainment, and Recreation', 'Finance and Insurance', 'Food Manufacturing', 'Real Estate and Rental and Leasing - Residual',
             'Lessors of Real Estate', 'Offices of Real Estate Agents and Broker', 'Real Estate', 'Activities Related to Real Estate', 'Administrative and Support and Waste Ser',
              'Transportation and Warehousing', 'Elementary and Secondary Schools', 'Colleges, Universities and Professional',]

In [44]:
edd_test5 = edd_test3.loc[~edd_test3['Industry Title'].isin(ind_to_cut)]

In [45]:
edd_test5['Current Employment'].sum()

15822420

In [46]:
edd_test5['Industry Title'].unique()

array(['Health Care and Social Assistance', 'Federal Government',
       'Local Government', 'Real Estate and Rental and Leasing',
       'Professional, Scientific and Technical S', 'Educational Services',
       'Accommodation and Food Service',
       'Management of Companies and Enterprises', 'State Government',
       'Special Districts plus Indian Tribes',
       'Private Service Providing - Residual',
       'Insurance Carriers and Related', 'Social Assistance',
       'Nursing and Residential Care Facilities', 'Hospitals',
       'Food and Beverage Stores', 'Ambulatory Health Care Services',
       'Waste Management and Remediation Service',
       'Food Services and Drinking Places', 'General Merchandise Stores',
       'Specialty Trade Contractors',
       'Administrative and Support Services', 'Department Stores',
       'Restaurants', 'Clothing and Clothing Accessories Stores',
       'Investigation and Security Services',
       'Merchant Wholesalers, Durable Goods',
       'Other Motor Vehicle Dealers',
       'Travel Arrangement and Reservation Servi',
       'Fabricated Metal Product Mfg', 'Primary Metal Manufacturing',
       'General Merchandise Stores, including Warehouse Clubs and Supercenters',
       'Automobile Dealers', 'Building Foundation and Exterior Contrac',
       'Architectural, Engineering and Related S',
       'Support Activities for Transportation',
       'Performing Arts, Spectator Sports',
       'Personal and Laundry Services',
       'Professional and Commercial Equipment Me',
       'Building Finishing Contractors',
       'Bakeries and Tortilla Manufacturing',
       'Building Material and Garden Equipment S',
       'Health and Personal Care Stores',
       'Management, Scientific and Technical Con', 'Gasoline Stations',
       'Couriers and Messengers',
       'Transportation Equipment Manufacturing',
       'Sporting Goods, Hobby and Musical Instru',
       'Chemical Manufacturing', 'Paper Manufacturing',
       'Printing and Related Support Activities',
       'Amusement, Gambling, and Recreation', 'Machinery Manufacturing',
       'Nonstore Retailers', 'Furniture and Home Furnishings Stores',
       'Repair and Maintenance', 'Utilities',
       'Limited-Service Eating Places', 'ResidualTextile Mills',
       'Furniture and Related Product Manufactur',
       'Agencies, Brokerages, and Other Insuranc',
       'Credit Intermediation and Related Activi',
       'Apparel Manufacturing',
       'Transit and Ground Passenger Transportat', 'Grocery Stores',
       'Telecommunications', 'Automotive Parts, Accessories and Tire S',
       'Cable and Other Subscription Programming',
       'Building Equipment Contractors', 'Full-Service Restaurants',
       'Broadcasting (except Internet)',
       'Offices of Other Health Practitioners',
       'Motor Vehicle and Parts Dealer',
       'Newspaper, Periodical, Book and Director',
       'Aerospace Product and Parts Manufacturin',
       'Household and Institutional Furniture Ma',
       'Pharmaceutical and Medicine Manufacturin',
       'Museums, Historical Sites, and Similar I',
       'Miscellaneous Durable Goods Merchant Who',
       'Machinery, Equipment and Supplies Mercha',
       'Religious, Grantmaking, Civic, Professio',
       'Grocery & Related Products Merchant whol',
       'Offices of Physicians', 'Publishing Industries (except Internet)',
       'Misc Nondurable Merchant Wholesalers',
       'Scientific Research and Development Serv',
       'Other Amusement and Recreation', 'Gambling Industries',
       'Electronic Instrument Manufacturing', 'Construction of Buildings',
       'Computer and Electronic Product Manufact',
       'Merchant Wholesalers, Nondurable Goods',
       'Petroleum and Coal Products Manufacturin',
       'Electrical Equipment and Appliance Manuf',
       'Apparel, Piece Gds & Notions Merch whole',
       'Computer Systems Design and Related Serv',
       'Advertising and Related Services', 'Insurance Carriers',
       'Book, Periodical and Music Stores',
       'Sporting Goods, Hobby, Book and Music St',
       'Securities, Commodity Contracts and Inve',
       'Warehousing and Storage',
       'Activities Related to Credit Intermediat', 'Offices of Dentists',
       'Motor Vehicle and Motor Vehicle Parts Me',
       'Electronics and Appliance Stores', 'Dairy Product Manufacturing',
       'Animal Slaughtering and Processing', 'Accommodation',
       'Child Day Care Services', 'Individual and Family Services',
       'Special Food Services', 'Services to Buildings and Dwellings',
       'Business Support Services',
       'Data Processing, Hosting & Related Services',
       'Miscellaneous Store Retailers',
       'Wholesale Electronic Markets and Agents',
       'Plastics and Rubber Products Manufacturi',
       'Miscellaneous Durable Goods Manufacturing',
       'Heavy and Civil Engineering Construction',
       'Nursing Care Facilities', 'Employment Services',
       'Motion Picture and Sound Recording',
       'Radio and Television Broadcasting', 'Legal Services',
       'Depository Credit Intermediation',
       'Nondepository Credit Intermediation',
       'Accounting, Tax Preparation and Bookkeep',
       'Electrical and Electronic Goods Merchant', 'Air Transportation',
       'Truck Transportation', 'Independent Artists, Writers, and Perfor',
       'Cut and Sew Apparel Manufacturing',
       'Other Specialty Trade Contract',
       'Beverage and Tobacco Product Mfg',
       'Semiconductor and Electronic Component M', 'Clothing Stores',
       'Ship and Boat Building', 'Software Publishers'], dtype=object)

In [47]:
edd_test5

,index,Area Type,Area Name,Year,Month,Date,Series Code,Industry Title,Seasonally Adjusted,Current Employment,series_code_str,last3,last4,last5
5,336605,County,Alameda,2020,December,12/01/2020,65620000,Health Care and Social Assistance,N,109400,65620000,000,0000,20000
14,336614,County,Alameda,2020,December,12/01/2020,90910000,Federal Government,N,8800,90910000,000,0000,10000
15,336615,County,Alameda,2020,December,12/01/2020,90930000,Local Government,N,71900,90930000,000,0000,30000
17,336617,County,Alameda,2020,December,12/01/2020,55530000,Real Estate and Rental and Leasing,N,9800,55530000,000,0000,30000
19,336619,County,Alameda,2020,December,12/01/2020,60540000,"Professional, Scientific and Technical S",N,76100,60540000,000,0000,40000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1992,338673,County,Yolo,2020,December,12/01/2020,90920000,State Government,N,25400,90920000,000,0000,20000
1996,338678,County,Yolo,2020,December,12/01/2020,60550000,Management of Companies and Enterprises,N,1100,60550000,000,0000,50000
1999,338681,County,Yuba,2020,December,12/01/2020,90920000,State Government,N,1000,90920000,000,0000,20000
2008,338691,County,Yuba,2020,December,12/01/2020,90910000,Federal Government,N,1400,90910000,000,0000,10000
2011,338694,County,Yuba,2020,December,12/01/2020,90930000,Local Government,N,4900,90930000,000,0000,30000

In [48]:
edd_test5.columns.values

array(['index', 'Area Type', 'Area Name', 'Year', 'Month', 'Date',
       'Series Code', 'Industry Title', 'Seasonally Adjusted',
       'Current Employment', 'series_code_str', 'last3', 'last4', 'last5'],
      dtype=object)

In [49]:
edd_test5 = edd_test5[['Area Name', 'Date', 'Industry Title', 'Series Code', 'Current Employment']]
# edd_test5.to_csv('cut_edd_2020.csv', index=False)

In [50]:
edd_test5

,Area Name,Date,Industry Title,Series Code,Current Employment
5,Alameda,12/01/2020,Health Care and Social Assistance,65620000,109400
14,Alameda,12/01/2020,Federal Government,90910000,8800
15,Alameda,12/01/2020,Local Government,90930000,71900
17,Alameda,12/01/2020,Real Estate and Rental and Leasing,55530000,9800
19,Alameda,12/01/2020,"Professional, Scientific and Technical S",60540000,76100
...,...,...,...,...,...
1992,Yolo,12/01/2020,State Government,90920000,25400
1996,Yolo,12/01/2020,Management of Companies and Enterprises,60550000,1100
1999,Yuba,12/01/2020,State Government,90920000,1000
2008,Yuba,12/01/2020,Federal Government,90910000,1400
2011,Yuba,12/01/2020,Local Government,90930000,4900