thoughts:
different counties are also going to need different industries--not all are using the level of industries
- example:

In [1]:
import pandas as pd
import numpy as np

Load and brief clean of EDD data

In [2]:
full_edd = pd.read_csv('Current_EDD_1121.csv')

In [3]:
full_edd['Area Name'] = full_edd['Area Name'].str.replace(' County', '')

Load county info data to get regions in the EDD dataset

In [56]:
county_info = pd.read_csv('~/classes/CAFWD/job_quality_index/data/county_to_regions_key.csv')

In [57]:
county_info.head()

   FIPS  COUNTYFIP        County Rural/Urban   Regions
0  6001          1       Alameda       Urban  Bay Area
1  6013         13  Contra Costa       Urban  Bay Area
2  6095         95        Solano       Urban  Bay Area
3  6081         81     San Mateo       Urban  Bay Area
4  6085         85   Santa Clara       Urban  Bay Area

Merge counties and EDD

In [59]:
full_edd_regions = pd.merge(full_edd, county_info, left_on='Area Name', right_on='County')

In [60]:
full_edd_regions.head(10)

,Area Type,Area Name,Year,Month,Date,Series Code,Industry Title,Seasonally Adjusted,Current Employment,FIPS,COUNTYFIP,County,Rural/Urban,Regions
0,County,Alameda,2014,January,01/01/2014,6000000,Goods Producing,N,100000,6001,1,Alameda,Urban,Bay Area
1,County,Alameda,2014,January,01/01/2014,70710000,"Arts, Entertainment, and Recreation",N,8800,6001,1,Alameda,Urban,Bay Area
2,County,Alameda,2014,January,01/01/2014,80000000,Other Services,N,24400,6001,1,Alameda,Urban,Bay Area
3,County,Alameda,2014,January,01/01/2014,65000000,Educational and Health Services,N,110700,6001,1,Alameda,Urban,Bay Area
4,County,Alameda,2014,January,01/01/2014,50000000,Information,N,13900,6001,1,Alameda,Urban,Bay Area
5,County,Alameda,2014,January,01/01/2014,65620000,Health Care and Social Assistance,N,95300,6001,1,Alameda,Urban,Bay Area
6,County,Alameda,2014,January,01/01/2014,70000000,Leisure and Hospitality,N,61800,6001,1,Alameda,Urban,Bay Area
7,County,Alameda,2014,January,01/01/2014,32000000,Nondurable Goods,N,21100,6001,1,Alameda,Urban,Bay Area
8,County,Alameda,2014,January,01/01/2014,42000000,Retail Trade,N,68500,6001,1,Alameda,Urban,Bay Area
9,County,Alameda,2014,January,01/01/2014,60560000,Administrative and Support and Waste Ser,N,35200,6001,1,Alameda,Urban,Bay Area

For testing, reduce down to December 2020

In [62]:
edd_test_2020 = full_edd_regions.loc[full_edd_regions['Date'] == '12/01/2020']

In [63]:
edd_test_2020 = edd_test_2020.loc[edd_test_2020['Seasonally Adjusted'] == 'N']

In [64]:
total_nonfarm = edd_test_2020.loc[edd_test_2020['Series Code'] == 0]

In [65]:
edd_test_2020 = edd_test_2020.loc[edd_test_2020['Series Code'] != 0]

In [66]:
edd_test_2020 = edd_test_2020.reset_index()

In [67]:
edd_test_2020

,index,Area Type,Area Name,Year,Month,Date,Series Code,Industry Title,Seasonally Adjusted,Current Employment,FIPS,COUNTYFIP,County,Rural/Urban,Regions
0,2656,County,Alameda,2020,December,12/01/2020,50000000,Information,N,19500,6001,1,Alameda,Urban,Bay Area
1,2657,County,Alameda,2020,December,12/01/2020,65000000,Educational and Health Services,N,122700,6001,1,Alameda,Urban,Bay Area
2,2658,County,Alameda,2020,December,12/01/2020,60560000,Administrative and Support and Waste Ser,N,38000,6001,1,Alameda,Urban,Bay Area
3,2659,County,Alameda,2020,December,12/01/2020,32000000,Nondurable Goods,N,20900,6001,1,Alameda,Urban,Bay Area
4,2660,County,Alameda,2020,December,12/01/2020,65620000,Health Care and Social Assistance,N,109400,6001,1,Alameda,Urban,Bay Area
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2013,674059,County,Yuba,2020,December,12/01/2020,70000000,Leisure and Hospitality,N,1000,6115,115,Yuba,Rural,Sacramento
2014,674060,County,Yuba,2020,December,12/01/2020,80000000,Other Services,N,300,6115,115,Yuba,Rural,Sacramento
2015,674061,County,Yuba,2020,December,12/01/2020,42000000,Retail Trade,N,1400,6115,115,Yuba,Rural,Sacramento
2016,674062,County,Yuba,2020,December,12/01/2020,50000000,Information,N,100,6115,115,Yuba,Rural,Sacramento
2017,674063,County,Yuba,2020,December,12/01/2020,65000000,Educational and Health Services,N,3700,6115,115,Yuba,Rural,Sacramento

In [68]:
edd_test_2020['Current Employment'].sum()

89599820

TARGET ISH COUNT OF WHAT TOTAL EMPLOYMENT SHOULD BE

In [69]:
len(total_nonfarm)

58

In [70]:
total_nonfarm['Current Employment'].sum()

15779100

In [71]:
edd_test_2020.loc[edd_test_2020['Series Code'] == 11000000]['Current Employment'].sum() # total farm

359520

In [16]:
target = 15779100 + 359520 # total farm + total nonfarm
target

16138620

Group by regions

In [79]:
edd_regions_2020 = edd_test_2020.groupby(['Regions', 'Industry Title', 'Series Code']).sum().reset_index()

In [81]:
edd_regions_2020 = edd_regions_2020[['Regions', 'Industry Title', 'Series Code', 'Current Employment']]

In [82]:
edd_regions_2020

,Regions,Industry Title,Series Code,Current Employment
0,Bay Area,Accommodation and Food Service,70720000,155800
1,Bay Area,Administrative and Support Services,60561000,14500
2,Bay Area,Administrative and Support and Waste Ser,60560000,187300
3,Bay Area,"Arts, Entertainment, and Recreation",70710000,19400
4,Bay Area,Beverage and Tobacco Product Mfg,32312000,10100
...,...,...,...,...
701,Sierra Nevada,Total Private,5000000,69850
702,Sierra Nevada,Total Wage and Salary,1000000,105950
703,Sierra Nevada,"Trade, Transportation and Utilities",40000000,15530
704,Sierra Nevada,"Transportation, Warehousing and Utilitie",43000000,1910
705,Sierra Nevada,Wholesale Trade,41000000,980

In [84]:
edd_regions_2020.loc[edd_regions_2020['Regions'] == 'Bay Area']

,Regions,Industry Title,Series Code,Current Employment
0,Bay Area,Accommodation and Food Service,70720000,155800
1,Bay Area,Administrative and Support Services,60561000,14500
2,Bay Area,Administrative and Support and Waste Ser,60560000,187300
3,Bay Area,"Arts, Entertainment, and Recreation",70710000,19400
4,Bay Area,Beverage and Tobacco Product Mfg,32312000,10100
5,Bay Area,City,90939022,6900
6,Bay Area,Clothing and Clothing Accessories Stores,42448000,1900
7,Bay Area,Construction,20000000,83300
8,Bay Area,County,90939012,11700
9,Bay Area,Department of Defense,90919110,0
10,Bay Area,Durable Goods,31000000,253600
11,Bay Area,Educational Services,65610000,88500
12,Bay Area,Educational and Health Services,65000000,594700
13,Bay Area,Federal Government,90910000,46700
14,Bay Area,Federal Government excluding Department of Def...,90912991,700
15,Bay Area,Finance and Insurance,55520000,128400
16,Bay Area,Financial Activities,55000000,191700
17,Bay Area,Food Services and Drinking Places,70722000,26100
18,Bay Area,Food and Beverage Stores,42445000,11000
19,Bay Area,General Merchandise Stores,42452000,7200
20,Bay Area,Goods Producing,6000000,555700
21,Bay Area,Government,90000000,451800
22,Bay Area,Health Care and Social Assistance,65620000,481200
23,Bay Area,Information,50000000,246400
24,Bay Area,Leisure and Hospitality,70000000,245700
25,Bay Area,Local Government,90930000,308500
26,Bay Area,Local Government Education,90931611,27000
27,Bay Area,Local Government Excluding Education,90932000,26100
28,Bay Area,Management of Companies and Enterprises,60550000,64700
29,Bay Area,Manufacturing,30000000,353700
30,Bay Area,Mining and Logging,10000000,800
31,Bay Area,"Natural Resources, Mining and Constructi",15000000,152200
32,Bay Area,Nondurable Goods,32000000,88600
33,Bay Area,Other Services,80000000,97300
34,Bay Area,Private Service Providing,8000000,323400
35,Bay Area,Professional and Business Services,60000000,760400
36,Bay Area,"Professional, Scientific and Technical S",60540000,483800
37,Bay Area,Real Estate and Rental and Leasing,55530000,51700
38,Bay Area,Restaurants,70722500,9900
39,Bay Area,Retail Trade,42000000,314700
40,Bay Area,Service Providing,7000000,3128400
41,Bay Area,Special Districts plus Indian Tribes,90932994,7500
42,Bay Area,Specialty Trade Contractors,20238000,10300
43,Bay Area,State Government,90920000,96600
44,Bay Area,State Government Education,90921611,2000
45,Bay Area,State Government Excluding Education,90922000,8200
46,Bay Area,State and Local Government,90940000,66900
47,Bay Area,Total Farm,11000000,14600
48,Bay Area,Total Private,5000000,413700
49,Bay Area,Total Wage and Salary,1000000,3698700
50,Bay Area,"Trade, Transportation and Utilities",40000000,540400
51,Bay Area,"Transportation, Warehousing and Utilitie",43000000,121000
52,Bay Area,Wholesale Trade,41000000,104700

In [74]:
edd_test_2020.loc[edd_test_2020['Industry Title'] == 'Accommodation and Food Service']

,index,Area Type,Area Name,Year,Month,Date,Series Code,Industry Title,Seasonally Adjusted,Current Employment,FIPS,COUNTYFIP,County,Rural/Urban,Regions
23,2679,County,Alameda,2020,December,12/01/2020,70720000,Accommodation and Food Service,N,40800,6001,1,Alameda,Urban,Bay Area
161,50986,County,Contra Costa,2020,December,12/01/2020,70720000,Accommodation and Food Service,N,25000,6013,13,Contra Costa,Urban,Bay Area
212,67808,County,El Dorado,2020,December,12/01/2020,70720000,Accommodation and Food Service,N,5800,6017,17,El Dorado,Rural,Sacramento
238,79647,County,Fresno,2020,December,12/01/2020,70720000,Accommodation and Food Service,N,25800,6019,19,Fresno,Urban,Central Valley
413,133935,County,Kern,2020,December,12/01/2020,70720000,Accommodation and Food Service,N,19600,6029,29,Kern,Urban,Central Valley
509,167155,County,Yolo,2020,December,12/01/2020,70720000,Accommodation and Food Service,N,5400,6113,113,Yolo,Rural,Sacramento
655,197886,County,Los Angeles,2020,December,12/01/2020,70720000,Accommodation and Food Service,N,292600,6037,37,Los Angeles,Urban,Los Angeles
927,306234,County,Monterey,2020,December,12/01/2020,70720000,Accommodation and Food Service,N,15900,6053,53,Monterey,Urban,Central Coast
949,319168,County,Napa,2020,December,12/01/2020,70720000,Accommodation and Food Service,N,7800,6055,55,Napa,Rural,Bay Area
1024,344141,County,Orange,2020,December,12/01/2020,70720000,Accommodation and Food Service,N,121600,6059,59,Orange,Urban,Orange
1115,371247,County,Placer,2020,December,12/01/2020,70720000,Accommodation and Food Service,N,14800,6061,61,Placer,Rural,Sacramento
1172,389687,County,Riverside,2020,December,12/01/2020,70720000,Accommodation and Food Service,N,61600,6065,65,Riverside,Urban,Inland Empire
1189,399935,County,Sacramento,2020,December,12/01/2020,70720000,Accommodation and Food Service,N,42400,6067,67,Sacramento,Urban,Sacramento
1253,419697,County,San Bernardino,2020,December,12/01/2020,70720000,Accommodation and Food Service,N,53700,6071,71,San Bernardino,Urban,Inland Empire
1335,435818,County,San Diego,2020,December,12/01/2020,70720000,Accommodation and Food Service,N,115600,6073,73,San Diego,Urban,San Diego-Imperial
1384,462783,County,San Francisco,2020,December,12/01/2020,70720000,Accommodation and Food Service,N,37400,6075,75,San Francisco,Urban,Bay Area
1440,474662,County,San Joaquin,2020,December,12/01/2020,70720000,Accommodation and Food Service,N,15900,6077,77,San Joaquin,Urban,Central Valley
1465,490505,County,San Luis Obispo,2020,December,12/01/2020,70720000,Accommodation and Food Service,N,12800,6079,79,San Luis Obispo,Rural,Central Coast
1509,501917,County,San Mateo,2020,December,12/01/2020,70720000,Accommodation and Food Service,N,20600,6081,81,San Mateo,Urban,Bay Area
1536,513355,County,Santa Barbara,2020,December,12/01/2020,70720000,Accommodation and Food Service,N,17400,6083,83,Santa Barbara,Urban,Central Coast
1604,537712,County,Santa Cruz,2020,December,12/01/2020,70720000,Accommodation and Food Service,N,7200,6087,87,Santa Cruz,Urban,Central Coast
1648,548634,County,Shasta,2020,December,12/01/2020,70720000,Accommodation and Food Service,N,4300,6089,89,Shasta,Rural,Shasta / Cascades
1705,572449,County,Solano,2020,December,12/01/2020,70720000,Accommodation and Food Service,N,10700,6095,95,Solano,Urban,Bay Area
1769,587120,County,Sonoma,2020,December,12/01/2020,70720000,Accommodation and Food Service,N,13500,6097,97,Sonoma,Rural,Bay Area
1898,636510,County,Tulare,2020,December,12/01/2020,70720000,Accommodation and Food Service,N,8700,6107,107,Tulare,Rural,Central Valley
1960,658956,County,Ventura,2020,December,12/01/2020,70720000,Accommodation and Food Service,N,24100,6111,111,Ventura,Urban,Central Coast

make series code column as str for parsing/testing

In [17]:
edd_test_2020['series_code_str'] = edd_test_2020['Series Code'].astype(str)

In [18]:
ind_tuples = set()
for row in full_edd.iterrows():
    ind_tuples.add((row[1][5], row[1][6]))

In [19]:
sorted(ind_tuples)

[(0, 'Total Nonfarm'),
 (1000000, 'Total Wage and Salary'),
 (5000000, 'Total Private'),
 (6000000, 'Goods Producing'),
 (7000000, 'Service Providing'),
 (8000000, 'Private Service Providing'),
 (8999999, 'Private Service Providing - Residual'),
 (10000000, 'Mining and Logging'),
 (10113300, 'Logging'),
 (10210000, 'Mining'),
 (10211000, 'Oil & Gas Extraction'),
 (10212000, 'Mining, except Oil & Gas'),
 (10213000, 'Support Activities for Mining'),
 (11000000, 'Total Farm'),
 (15000000, 'Natural Resources, Mining and Constructi'),
 (20000000, 'Construction'),
 (20236000, 'Construction of Buildings'),
 (20236100, 'Residential Building Construction'),
 (20236200, 'Nonresidential Building Construction'),
 (20237000, 'Heavy and Civil Engineering Construction'),
 (20237100, 'Utility System Const.'),
 (20237200, 'L& Subdivision'),
 (20237300, 'Highway, Street, and Bridge Const'),
 (20237900, 'Other Heavy & Civil Engineer'),
 (20238000, 'Specialty Trade Contractors'),
 (20238100, 'Building Foundation and Exterior Contrac'),
 (20238200, 'Building Equipment Contractors'),
 (20238300, 'Building Finishing Contractors'),
 (20238900, 'Other Specialty Trade Contract'),
 (30000000, 'Manufacturing'),
 (31000000, 'Durable Goods'),
 (31321000, 'Wood Product Manufacturing'),
 (31321900, 'Other Wood Product Mfg.'),
 (31327000, 'Nonmetallic Mineral Product Mfg.'),
 (31331000, 'Primary Metal Manufacturing'),
 (31332000, 'Fabricated Metal Product Mfg'),
 (31332300, 'Architectural & Structural Metals Mfg.'),
 (31332700, 'Machine Shops & Threaded Product Mfg.'),
 (31332900, 'Other Fabricated Metal Product Mfg.'),
 (31333000, 'Machinery Manufacturing'),
 (31333200, 'Industrial Machinery Manufacturing'),
 (31333300, 'Commercial and Service Industry Manufact'),
 (31333500, 'Metalworking Machinery Mfg.'),
 (31333900, 'ResidualOther General Purpose Machinery'),
 (31334000, 'Computer and Electronic Product Manufact'),
 (31334100, 'Computer and Peripheral Equipment Manufa'),
 (31334111, 'Electronic Computer Manufacturing'),
 (31334200, 'Communications Equipment Manufacturing'),
 (31334400, 'Semiconductor and Electronic Component M'),
 (31334412, 'Bare Printed Circuit Board Manufacturing'),
 (31334413, 'Semiconductor and Related Devices Manufa'),
 (31334500, 'Electronic Instrument Manufacturing'),
 (31335000, 'Electrical Equipment and Appliance Manuf'),
 (31336000, 'Transportation Equipment Manufacturing'),
 (31336100, 'Motor Vehicle Mfg.'),
 (31336400, 'Aerospace Product and Parts Manufacturin'),
 (31336600, 'Ship and Boat Building'),
 (31337000, 'Furniture and Related Product Manufactur'),
 (31337100, 'Household and Institutional Furniture Ma'),
 (31339000, 'Miscellaneous Durable Goods Manufacturing'),
 (31339100, 'Medical Equipment & Supplies Mfg.'),
 (31339900, 'Other Miscellaneous Durable Goods Mfg.'),
 (32000000, 'Nondurable Goods'),
 (32311000, 'Food Manufacturing'),
 (32311400, 'Fruit & Vegetable Preserving & Specialty'),
 (32311500, 'Dairy Product Manufacturing'),
 (32311600, 'Animal Slaughtering and Processing'),
 (32311800, 'Bakeries and Tortilla Manufacturing'),
 (32311900, 'Other Food Mfg.'),
 (32312000, 'Beverage and Tobacco Product Mfg'),
 (32313000, 'ResidualTextile Mills'),
 (32314000, 'Textile Product Mills'),
 (32315000, 'Apparel Manufacturing'),
 (32315100, 'Apparel Knitting Mills'),
 (32315200, 'Cut and Sew Apparel Manufacturing'),
 (32322000, 'Paper Manufacturing'),
 (32322200, 'Converted Paper Product Mfg.'),
 (32323000, 'Printing and Related Support Activities'),
 (32324000, 'Petroleum and Coal Products Manufacturin'),
 (32325000, 'Chemical Manufacturing'),
 (32325400, 'Pharmaceutical and Medicine Manufacturin'),
 (32325600, 'Soap, Cleaning Compound & Toiletry Mfg.'),
 (32326000, 'Plastics and Rubber Products Manufacturi'),
 (40000000, 'Trade, Transportation and Utilities'),
 (41000000, 'Wholesale Trade'),
 (41423000, 'Merchant Wholesalers, Durable Goods'),
 (41423100, 'Motor Vehicle and Motor Vehicle Parts Me'),
 (41423200, 'Furniture & Home Furnish Merch whole'),
 (41423300, 'Lumber & Other Const. Mat Merch whole'),
 (41423400, 'Professional and Commercial Equipment Me'),
 (41423600, 'Electrical and Electronic Goods Merchant'),
 (41423700, 'Hdwr, Plumb & Heating Merchant whole'),
 (41423800, 'Machinery, Equipment and Supplies Mercha'),
 (41423900, 'Miscellaneous Durable Goods Merchant Who'),
 (41424000, 'Merchant Wholesalers, Nondurable Goods'),
 (41424100, 'Paper & Paper Products Merchant whole'),
 (41424300, 'Apparel, Piece Gds & Notions Merch whole'),
 (41424400, 'Grocery & Related Products Merchant whol'),
 (41424600, 'Chemical & Allied Products Merchant whol'),
 (41424900, 'Misc Nondurable Merchant Wholesalers'),
 (41425000, 'Wholesale Electronic Markets and Agents'),
 (42000000, 'Retail Trade'),
 (42441000, 'Motor Vehicle and Parts Dealer'),
 (42441100, 'Automobile Dealers'),
 (42441200, 'Other Motor Vehicle Dealers'),
 (42441300, 'Automotive Parts, Accessories and Tire S'),
 (42442000, 'Furniture and Home Furnishings Stores'),
 (42442100, 'Furniture Stores'),
 (42442200, 'Home Furnishings Stores'),
 (42443000, 'Electronics and Appliance Stores'),
 (42444000, 'Building Material and Garden Equipment S'),
 (42444100, 'Building Material and Supplies Dealers'),
 (42445000, 'Food and Beverage Stores'),
 (42445100, 'Grocery Stores'),
 (42445200, 'Specialty Food Stores'),
 (42445300, 'Beer, Wine, & Liquor Stores'),
 (42446000, 'Health and Personal Care Stores'),
 (42447000, 'Gasoline Stations'),
 (42448000, 'Clothing and Clothing Accessories Stores'),
 (42448100, 'Clothing Stores'),
 (42448300, 'Jewelry, Luggage & Leather Gds Stores'),
 (42451000, 'Sporting Goods, Hobby, Book and Music St'),
 (42451100, 'Sporting Goods, Hobby and Musical Instru'),
 (42451200, 'Book, Periodical and Music Stores'),
 (42452000, 'General Merchandise Stores'),
 (42452200, 'Department Stores'),
 (42452300,
  'General Merchandise Stores, including Warehouse Clubs and Supercenters'),
 (42453000, 'Miscellaneous Store Retailers'),
 (42453200, 'Office Supplies, Stationery & Gift Store'),
 (42453300, 'Used Merch&ise Stores'),
 (42453900, 'Other Miscellaneous Store Retailers'),
 (42454000, 'Nonstore Retailers'),
 (42454100, 'Electronic Shopping & Mail-Order'),
 (43000000, 'Transportation, Warehousing and Utilitie'),
 (43220000, 'Utilities'),
 (43221100, 'Electric Power Gen, Trans & Distribution'),
 (43221200, 'Natural Gas Distribution'),
 (43400089, 'Transportation and Warehousing'),
 (43481000, 'Air Transportation'),
 (43481100, 'Scheduled Air transp.'),
 (43484000, 'Truck Transportation'),
 (43484100, 'General Freight Trucking'),
 (43484200, 'Specialized Freight Trucking'),
 (43485000, 'Transit and Ground Passenger Transportat'),
 (43488000, 'Support Activities for Transportation'),
 (43488300, 'Support Activities for Water transp.'),
 (43488400, 'Support Activities for Road transp.'),
 (43488500, 'Freight transp. Arrangement'),
 (43492000, 'Couriers and Messengers'),
 (43493000, 'Warehousing and Storage'),
 (50000000, 'Information'),
 (50511000, 'Publishing Industries (except Internet)'),
 (50511100, 'Newspaper, Periodical, Book and Director'),
 (50511200, 'Software Publishers'),
 (50512000, 'Motion Picture and Sound Recording'),
 (50512100, 'Motion Picture & Video Industries'),
 (50512110, 'Motion Picture & Video Production'),
 (50515000, 'Broadcasting (except Internet)'),
 (50515100, 'Radio and Television Broadcasting'),
 (50515200, 'Cable and Other Subscription Programming'),
 (50517000, 'Telecommunications'),
 (50517311, 'Wired Telecommunications Carriers'),
 (50518000, 'Data Processing, Hosting & Related Services'),
 (50519000, 'Other Information Serv.'),
 (55000000, 'Financial Activities'),
 (55520000, 'Finance and Insurance'),
 (55522000, 'Credit Intermediation and Related Activi'),
 (55522100, 'Depository Credit Intermediation'),
 (55522200, 'Nondepository Credit Intermediation'),
 (55522300, 'Activities Related to Credit Intermediat'),
 (55523000, 'Securities, Commodity Contracts and Inve'),
 (55523100, 'Securities & Commodity Contracts'),
 (55523900, 'Other Financial Investment Activities'),
 (55524000, 'Insurance Carriers and Related'),
 (55524100, 'Insurance Carriers'),
 (55524200, 'Agencies, Brokerages, and Other Insuranc'),
 (55530000, 'Real Estate and Rental and Leasing'),
 (55531000, 'Real Estate'),
 (55531100, 'Lessors of Real Estate'),
 (55531200, 'Offices of Real Estate Agents and Broker'),
 (55531300, 'Activities Related to Real Estate'),
 (55532000, 'Rental and Leasing Services'),
 (55532100, 'Automotive Equipment Rental and Leasing'),
 (55532200, 'Consumer Goods Rental'),
 (55532300, 'General Rental Centers'),
 (55532400, 'Comm & Industrial Mach Rental & Leasing'),
 (55539999, 'Real Estate and Rental and Leasing - Residual'),
 (60000000, 'Professional and Business Services'),
 (60540000, 'Professional, Scientific and Technical S'),
 (60541100, 'Legal Services'),
 (60541200, 'Accounting, Tax Preparation and Bookkeep'),
 (60541300, 'Architectural, Engineering and Related S'),
 (60541400, 'Specialized Design Services'),
 (60541500, 'Computer Systems Design and Related Serv'),
 (60541600, 'Management, Scientific and Technical Con'),
 (60541700, 'Scientific Research and Development Serv'),
 (60541800, 'Advertising and Related Services'),
 (60541900, 'Other Professional, Scientific and Techn'),
 (60550000, 'Management of Companies and Enterprises'),
 (60560000, 'Administrative and Support and Waste Ser'),
 (60561000, 'Administrative and Support Services'),
 (60561100, 'Office Administrative Services'),
 (60561200, 'Facilities Support Serv.'),
 (60561300, 'Employment Services'),
 (60561400, 'Business Support Services'),
 (60561500, 'Travel Arrangement and Reservation Servi'),
 (60561600, 'Investigation and Security Services'),
 (60561700, 'Services to Buildings and Dwellings'),
 (60561900, 'ResidualOther Support Services'),
 (60562000, 'Waste Management and Remediation Service'),
 (65000000, 'Educational and Health Services'),
 (65610000, 'Educational Services'),
 (65611100, 'Elementary and Secondary Schools'),
 (65611200, 'Junior Colleges'),
 (65611300, 'Colleges, Universities and Professional'),
 (65611600, 'Other Schools & Instruction'),
 (65620000, 'Health Care and Social Assistance'),
 (65621000, 'Ambulatory Health Care Services'),
 (65621100, 'Offices of Physicians'),
 (65621200, 'Offices of Dentists'),
 (65621300, 'Offices of Other Health Practitioners'),
 (65621400, 'Outpatient Care Centers'),
 (65621500, 'Medical & Diagnostic Laboratories'),
 (65621600, 'Home Health Care Serv.'),
 (65621900, 'Other Ambulatory Health Care Serv.'),
 (65622000, 'Hospitals'),
 (65622100, 'General Medical & Surgical Hosp.s'),
 (65622200, 'Psychiatric & Substance Abuse Hosp'),
 (65622300, 'Specialty (not Psych, Sub Abuse) Hosp.'),
 (65623000, 'Nursing and Residential Care Facilities'),
 (65623100, 'Nursing Care Facilities'),
 (65623200, 'Residential Intellectual & Developmental Disability'),
 (65623300, 'Comm Care Facilities for the Elderly'),
 (65623900, 'Other Residential Care Facilities'),
 (65624000, 'Social Assistance'),
 (65624100, 'Individual and Family Services'),
 (65624200, 'Community Food & Housing, & Emergency &'),
 (65624300, 'Vocational Rehabilitation Services'),
 (65624400, 'Child Day Care Services'),
 (70000000, 'Leisure and Hospitality'),
 (70710000, 'Arts, Entertainment, and Recreation'),
 (70711000, 'Performing Arts, Spectator Sports'),
 (70711100, 'Performing Arts Companies'),
 (70711200, 'Spectator Sports'),
 (70711500, 'Independent Artists, Writers, and Perfor'),
 (70712000, 'Museums, Historical Sites, and Similar I'),
 (70713000, 'Amusement, Gambling, and Recreation'),
 (70713100, 'Amusement Parks and Arcades'),
 (70713200, 'Gambling Industries'),
 (70713900, 'Other Amusement and Recreation'),
 (70720000, 'Accommodation and Food Service'),
 (70721000, 'Accommodation'),
 (70722000, 'Food Services and Drinking Places'),
 (70722300, 'Special Food Services'),
 (70722400, 'Drinking Places (Alcoholic Beverages)'),
 (70722500, 'Restaurants'),
 (70722511, 'Full-Service Restaurants'),
 (70722590, 'Limited-Service Eating Places'),
 (80000000, 'Other Services'),
 (80811000, 'Repair and Maintenance'),
 (80811100, 'Auto Repair & Maintenance'),
 (80811300, 'Commercial & Industrial Machinery'),
 (80811400, 'Personal & Household Goods Repair'),
 (80812000, 'Personal and Laundry Services'),
 (80812100, 'Personal Care Serv.'),
 (80812300, 'Drycleaning & Laundry Serv.'),
 (80812900, 'Other Personal Services'),
 (80813000, 'Religious, Grantmaking, Civic, Professio'),
 (80813100, 'Religious Organizations'),
 (80813200, 'Grantmaking & Giving Serv.'),
 (80813300, 'Social Advocacy Organizations'),
 (80813400, 'Civic & Social Organizations'),
 (80813900, 'Bus,Labor, Political & Other like Org.'),
 (90000000, 'Government'),
 (90910000, 'Federal Government'),
 (90912991, 'Federal Government excluding Department of Defense'),
 (90919110, 'Department of Defense'),
 (90920000, 'State Government'),
 (90921611, 'State Government Education'),
 (90922000, 'State Government Excluding Education'),
 (90930000, 'Local Government'),
 (90931150, 'Indian Tribes'),
 (90931611, 'Local Government Education'),
 (90932000, 'Local Government Excluding Education'),
 (90932994, 'Special Districts plus Indian Tribes'),
 (90939012, 'County'),
 (90939022, 'City'),
 (90939032, 'Special Districts'),
 (90940000, 'State and Local Government')]

In [20]:
selected_codes = [8999999, 11000000, 10000000, 15000000, 20236000, 20237000, 20238000, 31321000, 31327000, 31331000, 31332000, 31333000, 31334000, 31335000, 31336000, 31337000, 31339000,
32311000, 32312000, 32313000, 32314000, 32315000, 32322000, 32323000, 32324000, 32325000, 32326000, 41423000, 41424000, 41425000, 42441000, 42442000, 42443000, 42444000, 42445000, 42446000, 42447000, 42448000,
42451000, 42452000, 42453000, 42454000, 43220000, 43400089, 50511100, 50511200, 50512000, 50515100, 50515200, 50517000, 50518000, 50519000, 55522000, 55523000, 55524000, 55531000, 55532000,
60541100, 60541200, 60541300, 60541400, 60541500, 60541600, 60541700, 60541800, 60541900, 60550000, 60561000, 60562000, 65610000, 65621000, 65622000, 65623000, 65624000, 70711000, 70712000, 70713000, 70721000,
70722000, 80811000, 80812000, 80813000, 90910000, 90920000, 90930000]

In [21]:
# replaced all industries under "durable goods manufacturing" and "nondurable goods manufacturing" with these broader titles
selected_codes_2 = [8999999, 11000000, 10000000, 15000000, 20236000, 20237000, 20238000, 31000000,
32000000, 41423000, 41424000, 41425000, 42441000, 42442000, 42443000, 42444000, 42445000, 42446000, 42447000, 42448000,
42451000, 42452000, 42453000, 42454000, 43220000, 43400089, 50511100, 50511200, 50512000, 50515100, 50515200, 50517000, 50518000, 50519000, 55522000, 55523000, 55524000, 55531000, 55532000,
60541100, 60541200, 60541300, 60541400, 60541500, 60541600, 60541700, 60541800, 60541900, 60550000, 60561000, 60562000, 65610000, 65621000, 65622000, 65623000, 65624000, 70711000, 70712000, 70713000, 70721000,
70722000, 80811000, 80812000, 80813000, 90910000, 90920000, 90930000]

comments
- feeling unsure about codes starting with a 1
- used spreadsheet for reference - highlighting and going off initial scratch work

In [22]:
# for spot testing
full_edd[full_edd['Series Code'] == 8999999]

,Area Type,Area Name,Year,Month,Date,Series Code,Industry Title,Seasonally Adjusted,Current Employment
134,County,Colusa,2014,January,01/01/2014,8999999,Private Service Providing - Residual,N,330
792,County,Mariposa,2014,January,01/01/2014,8999999,Private Service Providing - Residual,N,220
876,County,Modoc,2014,January,01/01/2014,8999999,Private Service Providing - Residual,N,200
892,County,Mono,2014,January,01/01/2014,8999999,Private Service Providing - Residual,N,240
1922,County,Trinity,2014,January,01/01/2014,8999999,Private Service Providing - Residual,N,130
...,...,...,...,...,...,...,...,...,...
1312343,County,Trinity,1997,April,04/01/1997,8999999,Private Service Providing - Residual,N,250
1314607,County,Colusa,1997,May,05/01/1997,8999999,Private Service Providing - Residual,N,230
1315262,County,Mariposa,1997,May,05/01/1997,8999999,Private Service Providing - Residual,N,160
1315347,County,Modoc,1997,May,05/01/1997,8999999,Private Service Providing - Residual,N,230
1315362,County,Mono,1997,May,05/01/1997,8999999,Private Service Providing - Residual,N,260

In [23]:
edd_test = edd_test_2020.loc[edd_test_2020['Series Code'].isin(selected_codes_2)]

In [24]:
edd_test['Current Employment'].sum()

10576230

In [25]:
edd_test

,index,Area Type,Area Name,Year,Month,Date,Series Code,Industry Title,Seasonally Adjusted,Current Employment,series_code_str
0,335911,County,Yuba,2020,December,12/01/2020,11000000,Total Farm,N,400,11000000
4,336604,County,Alameda,2020,December,12/01/2020,32000000,Nondurable Goods,N,20900,32000000
11,336611,County,Alameda,2020,December,12/01/2020,11000000,Total Farm,N,600,11000000
14,336614,County,Alameda,2020,December,12/01/2020,90910000,Federal Government,N,8800,90910000
15,336615,County,Alameda,2020,December,12/01/2020,90930000,Local Government,N,71900,90930000
...,...,...,...,...,...,...,...,...,...,...,...
1996,338678,County,Yolo,2020,December,12/01/2020,60550000,Management of Companies and Enterprises,N,1100,60550000
1999,338681,County,Yuba,2020,December,12/01/2020,90920000,State Government,N,1000,90920000
2007,338690,County,Yuba,2020,December,12/01/2020,15000000,"Natural Resources, Mining and Constructi",N,1200,15000000
2008,338691,County,Yuba,2020,December,12/01/2020,90910000,Federal Government,N,1400,90910000
2011,338694,County,Yuba,2020,December,12/01/2020,90930000,Local Government,N,4900,90930000

### old testing - a more pythonic way, but less useful

**testing:** cut down series codes based on the number of zeros at the end and comparing employment counts

test 1: Ends with 2 zeros or less

In [26]:
parsed_codes = []
for i in range(len(edd_test_2020['series_code_str'])):
    parsed_codes.append(edd_test_2020['series_code_str'][i][-3:])
edd_test_2020['last3'] = parsed_codes

In [27]:
edd_test1 = edd_test_2020.loc[edd_test_2020['last3'] != '000']

In [28]:
edd_test1

,index,Area Type,Area Name,Year,Month,Date,Series Code,Industry Title,Seasonally Adjusted,Current Employment,series_code_str,last3
72,336677,County,Butte,2020,December,12/01/2020,90932994,Special Districts plus Indian Tribes,N,1400,90932994,994
88,336693,County,Butte,2020,December,12/01/2020,90921611,State Government Education,N,2800,90921611,611
126,336733,County,Colusa,2020,December,12/01/2020,8999999,Private Service Providing - Residual,N,200,8999999,999
230,336842,County,Fresno,2020,December,12/01/2020,90932994,Special Districts plus Indian Tribes,N,2500,90932994,994
242,336854,County,Fresno,2020,December,12/01/2020,90939022,City,N,5600,90939022,022
...,...,...,...,...,...,...,...,...,...,...,...,...
1946,338627,County,Ventura,2020,December,12/01/2020,90919110,Department of Defense,N,6000,90919110,110
1953,338634,County,Ventura,2020,December,12/01/2020,90921611,State Government Education,N,1300,90921611,611
1959,338640,County,Ventura,2020,December,12/01/2020,90931611,Local Government Education,N,19100,90931611,611
1960,338641,County,Ventura,2020,December,12/01/2020,90939012,County,N,8900,90939012,012
1967,338648,County,Ventura,2020,December,12/01/2020,43400089,Transportation and Warehousing,N,5500,43400089,089

In [29]:
edd_test1['Current Employment'].sum()

4918090

test 2: Ends with 3 zeros or less

In [30]:
parsed_codes = []
for i in range(len(edd_test_2020['series_code_str'])):
    parsed_codes.append(edd_test_2020['series_code_str'][i][-4:])
edd_test_2020['last4'] = parsed_codes

In [31]:
edd_test2 = edd_test_2020.loc[edd_test_2020['last4'] != '0000']

In [32]:
edd_test2

,index,Area Type,Area Name,Year,Month,Date,Series Code,Industry Title,Seasonally Adjusted,Current Employment,series_code_str,last3,last4
72,336677,County,Butte,2020,December,12/01/2020,90932994,Special Districts plus Indian Tribes,N,1400,90932994,994,2994
83,336688,County,Butte,2020,December,12/01/2020,90932000,Local Government Excluding Education,N,4400,90932000,000,2000
88,336693,County,Butte,2020,December,12/01/2020,90921611,State Government Education,N,2800,90921611,611,1611
126,336733,County,Colusa,2020,December,12/01/2020,8999999,Private Service Providing - Residual,N,200,8999999,999,9999
229,336841,County,Fresno,2020,December,12/01/2020,32311000,Food Manufacturing,N,12000,32311000,000,1000
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1960,338641,County,Ventura,2020,December,12/01/2020,90939012,County,N,8900,90939012,012,9012
1961,338642,County,Ventura,2020,December,12/01/2020,60561000,Administrative and Support Services,N,17100,60561000,000,1000
1966,338647,County,Ventura,2020,December,12/01/2020,42452000,General Merchandise Stores,N,5900,42452000,000,2000
1967,338648,County,Ventura,2020,December,12/01/2020,43400089,Transportation and Warehousing,N,5500,43400089,089,0089
1968,338649,County,Ventura,2020,December,12/01/2020,20238000,Specialty Trade Contractors,N,10900,20238000,000,8000

In [33]:
edd_test2['Current Employment'].sum()

10848490

test 3: Ends with 4 zeros or less

In [34]:
parsed_codes = []
for i in range(len(edd_test_2020['series_code_str'])):
    parsed_codes.append(edd_test_2020['series_code_str'][i][-5:])
edd_test_2020['last5'] = parsed_codes

In [35]:
edd_test3 = edd_test_2020.loc[edd_test_2020['last5'] != '00000']

In [36]:
edd_test3

,index,Area Type,Area Name,Year,Month,Date,Series Code,Industry Title,Seasonally Adjusted,Current Employment,series_code_str,last3,last4,last5
3,336603,County,Alameda,2020,December,12/01/2020,60560000,Administrative and Support and Waste Ser,N,38000,60560000,000,0000,60000
5,336605,County,Alameda,2020,December,12/01/2020,65620000,Health Care and Social Assistance,N,109400,65620000,000,0000,20000
9,336609,County,Alameda,2020,December,12/01/2020,70710000,"Arts, Entertainment, and Recreation",N,4900,70710000,000,0000,10000
14,336614,County,Alameda,2020,December,12/01/2020,90910000,Federal Government,N,8800,90910000,000,0000,10000
15,336615,County,Alameda,2020,December,12/01/2020,90930000,Local Government,N,71900,90930000,000,0000,30000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1996,338678,County,Yolo,2020,December,12/01/2020,60550000,Management of Companies and Enterprises,N,1100,60550000,000,0000,50000
1998,338680,County,Yolo,2020,December,12/01/2020,55520000,Finance and Insurance,N,1000,55520000,000,0000,20000
1999,338681,County,Yuba,2020,December,12/01/2020,90920000,State Government,N,1000,90920000,000,0000,20000
2008,338691,County,Yuba,2020,December,12/01/2020,90910000,Federal Government,N,1400,90910000,000,0000,10000
2011,338694,County,Yuba,2020,December,12/01/2020,90930000,Local Government,N,4900,90930000,000,0000,30000

In [37]:
edd_test3['Current Employment'].sum()

21279490

In [38]:
# edd_test3['Industry Title'].unique()

test 4: custom list of codes

In [39]:
custom_codes = [8999999, 15000000, 20236100, 20236200, 20237000, 20238100, 20238200, 20238300, 20238900, 31331000, 31332000, 31333000, 
31334400, 31334500, 31335000, 31336400, 31336600, 31337000, 31339000, 32311500, 32311600, 32311800, 32312000, 32313000, 32315000, 32322000, 32323000, 32324000, 32325000, 32326000, 41423100, 41423400,41423600,41423800,41423900, 41424300,41424400,41424900,41425000, 42441100,42441200, 42441300, 42442000, 42443000, 42444000, 42445000, 42446000, 42447000, 42448000, 42451000,42452000,42453000,42454000, 43220000,43400089,43481000,43484000,43485000,43488000,43492000,43493000, 50511000,50512000,50515000,50517000,50518000, 55522100,55522200,55522300,55523000,55524100,55524200, 55531100,55531200,55531300,55539999,60541100,60541200,60541300,60541500,60541600,60541700,60541800,60550000, 60561300,60561400,60561500,60561600,60561700,60562000,65611100,
 65611300,65621100,65621200, 65621300, 65622000, 65623000, 65624100, 65624400, 70711000, 70712000, 70713000, 70721000, 70722000, 80811000, 80812000,
 80813000, 90910000, 90920000, 90930000, 90940000]

In [40]:
edd_test4 = edd_test_2020.loc[edd_test_2020['Series Code'].isin(custom_codes)]

In [41]:
edd_test4

,index,Area Type,Area Name,Year,Month,Date,Series Code,Industry Title,Seasonally Adjusted,Current Employment,series_code_str,last3,last4,last5
14,336614,County,Alameda,2020,December,12/01/2020,90910000,Federal Government,N,8800,90910000,000,0000,10000
15,336615,County,Alameda,2020,December,12/01/2020,90930000,Local Government,N,71900,90930000,000,0000,30000
16,336616,County,Alameda,2020,December,12/01/2020,15000000,"Natural Resources, Mining and Constructi",N,48000,15000000,000,0000,00000
26,336626,County,Alameda,2020,December,12/01/2020,60550000,Management of Companies and Enterprises,N,15500,60550000,000,0000,50000
27,336627,County,Alameda,2020,December,12/01/2020,90920000,State Government,N,37000,90920000,000,0000,20000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1996,338678,County,Yolo,2020,December,12/01/2020,60550000,Management of Companies and Enterprises,N,1100,60550000,000,0000,50000
1999,338681,County,Yuba,2020,December,12/01/2020,90920000,State Government,N,1000,90920000,000,0000,20000
2007,338690,County,Yuba,2020,December,12/01/2020,15000000,"Natural Resources, Mining and Constructi",N,1200,15000000,000,0000,00000
2008,338691,County,Yuba,2020,December,12/01/2020,90910000,Federal Government,N,1400,90910000,000,0000,10000
2011,338694,County,Yuba,2020,December,12/01/2020,90930000,Local Government,N,4900,90930000,000,0000,30000

In [42]:
edd_test4['Current Employment'].sum()

9789830

test 5: take test 3 and cut specific industries that I know clearly overlap

In [43]:
# to exclude
ind_to_cut = ['State and Local Government', 'Local Government Excluding Education', 'State Government Education', 'Local Government Education', 'City', 'County', 'Department of Defense', 'Federal Government excluding Department of Defense', 'State Government Excluding Education', 'Residential Building Construction', 'Nonresidential Building Construction',
             'Arts, Entertainment, and Recreation', 'Finance and Insurance', 'Food Manufacturing', 'Real Estate and Rental and Leasing - Residual',
             'Lessors of Real Estate', 'Offices of Real Estate Agents and Broker', 'Real Estate', 'Activities Related to Real Estate', 'Administrative and Support and Waste Ser',
              'Transportation and Warehousing', 'Elementary and Secondary Schools', 'Colleges, Universities and Professional',]

In [44]:
edd_test5 = edd_test3.loc[~edd_test3['Industry Title'].isin(ind_to_cut)]

In [45]:
edd_test5['Current Employment'].sum()

15822420

In [46]:
edd_test5['Industry Title'].unique()

array(['Health Care and Social Assistance', 'Federal Government',
       'Local Government', 'Real Estate and Rental and Leasing',
       'Professional, Scientific and Technical S', 'Educational Services',
       'Accommodation and Food Service',
       'Management of Companies and Enterprises', 'State Government',
       'Special Districts plus Indian Tribes',
       'Private Service Providing - Residual',
       'Insurance Carriers and Related', 'Social Assistance',
       'Nursing and Residential Care Facilities', 'Hospitals',
       'Food and Beverage Stores', 'Ambulatory Health Care Services',
       'Waste Management and Remediation Service',
       'Food Services and Drinking Places', 'General Merchandise Stores',
       'Specialty Trade Contractors',
       'Administrative and Support Services', 'Department Stores',
       'Restaurants', 'Clothing and Clothing Accessories Stores',
       'Investigation and Security Services',
       'Merchant Wholesalers, Durable Goods',
       'Other Motor Vehicle Dealers',
       'Travel Arrangement and Reservation Servi',
       'Fabricated Metal Product Mfg', 'Primary Metal Manufacturing',
       'General Merchandise Stores, including Warehouse Clubs and Supercenters',
       'Automobile Dealers', 'Building Foundation and Exterior Contrac',
       'Architectural, Engineering and Related S',
       'Support Activities for Transportation',
       'Performing Arts, Spectator Sports',
       'Personal and Laundry Services',
       'Professional and Commercial Equipment Me',
       'Building Finishing Contractors',
       'Bakeries and Tortilla Manufacturing',
       'Building Material and Garden Equipment S',
       'Health and Personal Care Stores',
       'Management, Scientific and Technical Con', 'Gasoline Stations',
       'Couriers and Messengers',
       'Transportation Equipment Manufacturing',
       'Sporting Goods, Hobby and Musical Instru',
       'Chemical Manufacturing', 'Paper Manufacturing',
       'Printing and Related Support Activities',
       'Amusement, Gambling, and Recreation', 'Machinery Manufacturing',
       'Nonstore Retailers', 'Furniture and Home Furnishings Stores',
       'Repair and Maintenance', 'Utilities',
       'Limited-Service Eating Places', 'ResidualTextile Mills',
       'Furniture and Related Product Manufactur',
       'Agencies, Brokerages, and Other Insuranc',
       'Credit Intermediation and Related Activi',
       'Apparel Manufacturing',
       'Transit and Ground Passenger Transportat', 'Grocery Stores',
       'Telecommunications', 'Automotive Parts, Accessories and Tire S',
       'Cable and Other Subscription Programming',
       'Building Equipment Contractors', 'Full-Service Restaurants',
       'Broadcasting (except Internet)',
       'Offices of Other Health Practitioners',
       'Motor Vehicle and Parts Dealer',
       'Newspaper, Periodical, Book and Director',
       'Aerospace Product and Parts Manufacturin',
       'Household and Institutional Furniture Ma',
       'Pharmaceutical and Medicine Manufacturin',
       'Museums, Historical Sites, and Similar I',
       'Miscellaneous Durable Goods Merchant Who',
       'Machinery, Equipment and Supplies Mercha',
       'Religious, Grantmaking, Civic, Professio',
       'Grocery & Related Products Merchant whol',
       'Offices of Physicians', 'Publishing Industries (except Internet)',
       'Misc Nondurable Merchant Wholesalers',
       'Scientific Research and Development Serv',
       'Other Amusement and Recreation', 'Gambling Industries',
       'Electronic Instrument Manufacturing', 'Construction of Buildings',
       'Computer and Electronic Product Manufact',
       'Merchant Wholesalers, Nondurable Goods',
       'Petroleum and Coal Products Manufacturin',
       'Electrical Equipment and Appliance Manuf',
       'Apparel, Piece Gds & Notions Merch whole',
       'Computer Systems Design and Related Serv',
       'Advertising and Related Services', 'Insurance Carriers',
       'Book, Periodical and Music Stores',
       'Sporting Goods, Hobby, Book and Music St',
       'Securities, Commodity Contracts and Inve',
       'Warehousing and Storage',
       'Activities Related to Credit Intermediat', 'Offices of Dentists',
       'Motor Vehicle and Motor Vehicle Parts Me',
       'Electronics and Appliance Stores', 'Dairy Product Manufacturing',
       'Animal Slaughtering and Processing', 'Accommodation',
       'Child Day Care Services', 'Individual and Family Services',
       'Special Food Services', 'Services to Buildings and Dwellings',
       'Business Support Services',
       'Data Processing, Hosting & Related Services',
       'Miscellaneous Store Retailers',
       'Wholesale Electronic Markets and Agents',
       'Plastics and Rubber Products Manufacturi',
       'Miscellaneous Durable Goods Manufacturing',
       'Heavy and Civil Engineering Construction',
       'Nursing Care Facilities', 'Employment Services',
       'Motion Picture and Sound Recording',
       'Radio and Television Broadcasting', 'Legal Services',
       'Depository Credit Intermediation',
       'Nondepository Credit Intermediation',
       'Accounting, Tax Preparation and Bookkeep',
       'Electrical and Electronic Goods Merchant', 'Air Transportation',
       'Truck Transportation', 'Independent Artists, Writers, and Perfor',
       'Cut and Sew Apparel Manufacturing',
       'Other Specialty Trade Contract',
       'Beverage and Tobacco Product Mfg',
       'Semiconductor and Electronic Component M', 'Clothing Stores',
       'Ship and Boat Building', 'Software Publishers'], dtype=object)

In [47]:
edd_test5

,index,Area Type,Area Name,Year,Month,Date,Series Code,Industry Title,Seasonally Adjusted,Current Employment,series_code_str,last3,last4,last5
5,336605,County,Alameda,2020,December,12/01/2020,65620000,Health Care and Social Assistance,N,109400,65620000,000,0000,20000
14,336614,County,Alameda,2020,December,12/01/2020,90910000,Federal Government,N,8800,90910000,000,0000,10000
15,336615,County,Alameda,2020,December,12/01/2020,90930000,Local Government,N,71900,90930000,000,0000,30000
17,336617,County,Alameda,2020,December,12/01/2020,55530000,Real Estate and Rental and Leasing,N,9800,55530000,000,0000,30000
19,336619,County,Alameda,2020,December,12/01/2020,60540000,"Professional, Scientific and Technical S",N,76100,60540000,000,0000,40000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1992,338673,County,Yolo,2020,December,12/01/2020,90920000,State Government,N,25400,90920000,000,0000,20000
1996,338678,County,Yolo,2020,December,12/01/2020,60550000,Management of Companies and Enterprises,N,1100,60550000,000,0000,50000
1999,338681,County,Yuba,2020,December,12/01/2020,90920000,State Government,N,1000,90920000,000,0000,20000
2008,338691,County,Yuba,2020,December,12/01/2020,90910000,Federal Government,N,1400,90910000,000,0000,10000
2011,338694,County,Yuba,2020,December,12/01/2020,90930000,Local Government,N,4900,90930000,000,0000,30000

In [48]:
edd_test5.columns.values

array(['index', 'Area Type', 'Area Name', 'Year', 'Month', 'Date',
       'Series Code', 'Industry Title', 'Seasonally Adjusted',
       'Current Employment', 'series_code_str', 'last3', 'last4', 'last5'],
      dtype=object)

In [49]:
edd_test5 = edd_test5[['Area Name', 'Date', 'Industry Title', 'Series Code', 'Current Employment']]
# edd_test5.to_csv('cut_edd_2020.csv', index=False)

In [50]:
edd_test5

,Area Name,Date,Industry Title,Series Code,Current Employment
5,Alameda,12/01/2020,Health Care and Social Assistance,65620000,109400
14,Alameda,12/01/2020,Federal Government,90910000,8800
15,Alameda,12/01/2020,Local Government,90930000,71900
17,Alameda,12/01/2020,Real Estate and Rental and Leasing,55530000,9800
19,Alameda,12/01/2020,"Professional, Scientific and Technical S",60540000,76100
...,...,...,...,...,...
1992,Yolo,12/01/2020,State Government,90920000,25400
1996,Yolo,12/01/2020,Management of Companies and Enterprises,60550000,1100
1999,Yuba,12/01/2020,State Government,90920000,1000
2008,Yuba,12/01/2020,Federal Government,90910000,1400
2011,Yuba,12/01/2020,Local Government,90930000,4900